### ISSUE TITLE
[Vanilla Bug] Fixes to DebrisMaximums

### ISSUE THREAD

**Issue by SMxReaver** [Phobos-developers/Phobos#109]
**ORIGINALLY SUGGESTED BY MIRCEA**
Hi, any chance some of you gentleman know how to fix the Debris limitation 
So we can have the code working for YR (phobos) like it dose in TS

[TTNK]
MaxDebris=18
MinDebris=17
DebrisTypes=TTNK_H,DEBV1,DEBV2S,DEBV3,DEBV4,DEBV5,DEBV6,FIREVX,INVVX,INVVX2
DebrisMaximums=1,1,6,3,2,1,1,2,1,1

In TS works fine

In Origin version of YR only the first digit works. 

DebrisMaximums=1,1,6,3,2,1,1,2,1,1

In Ares the line is not working at all

DebrisMaximums=

So you get instances of, instead of a car hull flying with 2 weals flying off, you get 3 car hulls

![explotest4](https://user-images.githubusercontent.com/77598000/111914189-61059900-8a47-11eb-9c7a-7a96e7801d95.gif)

**Comment by Thrifinesma** [comment]
Resolved
