### ISSUE TITLE
Game crash on mission change

### ISSUE THREAD

**Issue by mevitar** [Phobos-developers/Phobos#1091]
### Description

After successfully launching & quitting a mission, the game will crash when trying to launch a different one.

It appears to be the same crash as this one (same EIP), except with different conditions: https://github.com/Phobos-developers/Phobos/issues/1074

### Phobos Version

https://github.com/Phobos-developers/Phobos/commit/4cc2adfee5927944cfca94f4301bd58b7c8b4702

### Steps to reproduce

1. Launch a mission.
2. Quit.
3. Start a new mission.
4. Despair as your game crashed and you don't know what is going on because the mission worked fine when you launched it first but now that you launch it second it crashes what is even going on i don't know anymore.

### Expected behaviour

The game should launch another mission properly.

### Actual behaviour

No matter what mission will be launched, it will work fine it launched as the first one, but crash when launched as the second one.

### Additional context

[except.zip](https://github.com/Phobos-developers/Phobos/files/11909715/except.zip)

### Checklist

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by FS-21** [comment]
This crash remembers me my case I commented in discord's channel months ago.

In my case I discovered I didn't declare an overlay in the overlays list in rulesmd.ini ...

**Comment by Falaka21** [comment]
> I don't know if it is because of Phobos but I have similar problems when creating a random map in vanilla skirmish game.

All caused by "fog.shp" file that I forget to delete...It causes ddraw.dll confuse  and  game engine couldn't handle it.I delete it and my RMG works as expected....Sorry.

**Comment by mevitar** [comment]
This issue has nothing to do with incorrectly declared overlay or fog.shp file.
No Phobos or pre-b34 Phobos: game works fine on reload.
b34 Phobos: doesn't work at all with my mod because new inheritance was implemented.
b35 Phobos: new inheritance is optional, game starts crashing on mission reload.

**Comment by mevitar** [comment]
It seems to be related to saving and reloading saves. If i start a campaign mission and remove the autosave, then quit and start again, the mission loads fine.
But if i start it and do not remove the autosave before restarting, the game crashes on mission load. Loading the save also crashes the game.

This doesn't seem to be an issue for vanilla YR or for mods that don't use inheritance at all. Don't know how mods that use Phobos inheritance behave.

**Comment by mevitar** [comment]
Since several builds i couldn't get this crash to happen again, so whatever was the cause must have been fixed at one point.
