### ISSUE TITLE
[Phobos Bug] 'LimboKill.Affects=' doesn't work

### ISSUE THREAD

**Issue by Zhcs0712** [Phobos-developers/Phobos#1096]
### Description

When I set the 'LimboKill.Affects=enemy' attribute of the SuperWeapon,own off-map buildings with designated IDs will also be removed.

### Phobos Version

b35

### INI code

```ini
[SuperWeapon1Special]
...
LimboDelivery.Types=FCNS
LimboDelivery.IDs=1000
...

[SuperWeapon2Special]
...
LimboKill.Affects=enemy
LimboKill.IDs=1000
...

[FCNS]
SuperWeapon=SuperWeaponNeeded
...
```

### Steps to reproduce

1.
2.
3.
...

### Expected behaviour

If the 'LimboKill.Affects=enemy' ,own off-map buildings with designated IDs will not be removed.The enemy will lose the
‘SuperWeaponNeeded' ,but I won't.

### Actual behaviour

All of the off-map buildings are removed.

### Checklist

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by MortonPL** [comment]
The correct entry name is `LimboKill.Affected`, not `LimboKill.Affects`. This was a mistake in documentation and has now been fixed.
