### ISSUE TITLE
Convert superweapon issue

### ISSUE THREAD

**Issue by reedom114514** [Phobos-developers/Phobos#1106]
### Description

1 when I convert a deployed GI into a troop, it cannot move.
2 AI would not continue the command of the converted units, they would stop here.
3 AI would not recognize new units as the old one, so AI would build the old units (as they ingore the build prerequisite).
4 If I put autofire on my convert superweapon, according to 2, AI would continuely build the old units, and as they are all converted, AI would not stop doing this.

### Phobos Version

B36

### Conditions to reproduce

MO3, normal syringe, a little bit change in rules.

### INI code

```ini
[ArsenalMedicSpawn]
......
Convert0.From=E1                  ; list of TechnoTypes
Convert0.To=ARND                    ; TechnoType
Convert0.AffectedHouses=owner     ; list of Affected House Enumeration (none|owner/self|allies/ally|team|enemies/enemy|all)
LimboDelivery.Types=UPGRADEBD

[E1]
Prerequisite.Negative=UPGRADEBD
```

### Steps to reproduce

1. building barracks to train GI
2. building arsenal
3. seeing what happens

### Expected behaviour

AI would building new GI rather than the old ones, the new GI would act as normal.

### Actual behaviour

New GI stopped, and AIs are still building normal GI.

### Additional context

![XBZS F~2SOZN%3)72V5N8(B](https://github.com/Phobos-developers/Phobos/assets/117975708/3b772ed0-b0e1-4d9c-b041-e4f3fe1026c3)
![`E}4$7Z)U_$SF}T 5_BTSS0](https://github.com/Phobos-developers/Phobos/assets/117975708/ee573205-7997-4910-94ff-726affbe09ff)

### Checklist

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by MortonPL** [comment]
>1 when I convert a deployed GI into a troop, it cannot move.
>2 AI would not continue the command of the converted units, they would stop here.

Can you see if the same happens when you convert them by [Ares methods](https://ares-developers.github.io/Ares-docs/new/typeconversion.html) like promotion? If yes, then we won't be able to do much about it.

**Comment by Metadorius** [comment]
Actually if we have access to the unit pre and post conversion, fixing up the deploy and AI state may be trivial. It would only work for Phobos-initiated conversion though.

**Comment by reedom114514** [comment]
> > 1 when I convert a deployed GI into a troop, it cannot move.
> > 2 AI would not continue the command of the converted units, they would stop here.
> 
> Can you see if the same happens when you convert them by [Ares methods](https://ares-developers.github.io/Ares-docs/new/typeconversion.html) like promotion? If yes, then we won't be able to do much about it.

yes, about the first problem, I am sure it is still the same in ares

**Comment by TaranDahl** [comment]
但我们认为这是正常的（iksar脸）
我认为使用kratos或者pr#352的替身机制可能可以一定程度上解决你的问题：给变形后的单位挂上变身前的单位替身，可以作为buildlimit之类的限制。不过ai会怎么处置它我就不确定了，我没怎么写过ai。
