### ISSUE TITLE
When I press "esc" key and get a game crush on game.

### ISSUE THREAD

**Issue by PacrateOfficial** [Phobos-developers/Phobos#1107]
### Description

When I press "esc" key and get a game crush on game.
This is a "Exception code: C0000005 at 61288900".

### Phobos Version

B36

### Conditions to reproduce

Mental Omega 3, I want to change the INI file, but I don't know which of its codes have this phenomenon.
This is a guess only.

### INI code

```ini
No response
```

### Steps to reproduce

1.Launch a campaign or skirmish.
2.Press "esc" key or Click menu.
3.Immediately get a game crush.
4.I don't know why this phenomenon appears.

### Expected behaviour

It should not appear the phenomenon.

### Actual behaviour

When I press "esc" key or Click menu on Screen of Northeast and get a game crush on game.

### Additional context

[debug.log](https://github.com/Phobos-developers/Phobos/files/12081156/debug.log)
[except.txt](https://github.com/Phobos-developers/Phobos/files/12081157/except.txt)
[syringe.log](https://github.com/Phobos-developers/Phobos/files/12081158/syringe.log)

https://github.com/Phobos-developers/Phobos/assets/139878231/8a894c10-3e7f-4fcc-8d32-80e4ffc8e87c

### Checklist

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by Metadorius** [comment]
Please, upload the `extcrashdump.dmp` file (you may archive it and split into multiple files around 20mb size to upload here) from the snapshot folder that got created when you pressed "yes" button on the crash message. It will help us know what caused the crash.

**Comment by PacrateOfficial** [comment]
[extcrashdump.part01.zip](https://github.com/Phobos-developers/Phobos/files/12081458/extcrashdump.part01.zip)
[extcrashdump.part02.zip](https://github.com/Phobos-developers/Phobos/files/12081460/extcrashdump.part02.zip)
[extcrashdump.part03.zip](https://github.com/Phobos-developers/Phobos/files/12081462/extcrashdump.part03.zip)
[extcrashdump.part04.zip](https://github.com/Phobos-developers/Phobos/files/12081464/extcrashdump.part04.zip)
[extcrashdump.part05.zip](https://github.com/Phobos-developers/Phobos/files/12081466/extcrashdump.part05.zip)
[extcrashdump.part06.zip](https://github.com/Phobos-developers/Phobos/files/12081469/extcrashdump.part06.zip)
[extcrashdump.part07.zip](https://github.com/Phobos-developers/Phobos/files/12081472/extcrashdump.part07.zip)
[extcrashdump.zip](https://github.com/Phobos-developers/Phobos/files/12081473/extcrashdump.zip)

**Comment by PacrateOfficial** [comment]
> Please, upload the `extcrashdump.dmp` file (you may archive it and split into multiple files around 20mb size to upload here) from the snapshot folder that got created when you pressed "yes" button on the crash message. It will help us know what caused the crash.

Sorry,I don't know how to upload it.And this file is too large.

**Comment by PacrateOfficial** [comment]
[extcrashdump.z01.zip](https://github.com/Phobos-developers/Phobos/files/12081920/extcrashdump.z01.zip)
[extcrashdump.z02.zip](https://github.com/Phobos-developers/Phobos/files/12081928/extcrashdump.z02.zip)
[extcrashdump.z03.zip](https://github.com/Phobos-developers/Phobos/files/12081931/extcrashdump.z03.zip)
[extcrashdump.z04.zip](https://github.com/Phobos-developers/Phobos/files/12081933/extcrashdump.z04.zip)
[extcrashdump.z05.zip](https://github.com/Phobos-developers/Phobos/files/12081935/extcrashdump.z05.zip)
[extcrashdump.z06.zip](https://github.com/Phobos-developers/Phobos/files/12081941/extcrashdump.z06.zip)
[extcrashdump.z07.zip](https://github.com/Phobos-developers/Phobos/files/12081948/extcrashdump.z07.zip)
[extcrashdump.zip](https://github.com/Phobos-developers/Phobos/files/12081950/extcrashdump.zip)
Please the files name suffix "zip" of "z01" to "z07" are deleted.

**Comment by reedom114514** [comment]
I have this issue too, newest nightly build with cnc-ddraw.
[extcrashdump.z06.zip](https://github.com/Phobos-developers/Phobos/files/12284949/extcrashdump.z06.zip)
[extcrashdump.zip](https://github.com/Phobos-developers/Phobos/files/12284952/extcrashdump.zip)
[snapshot-20230808-041234.zip](https://github.com/Phobos-developers/Phobos/files/12284953/snapshot-20230808-041234.zip)
[extcrashdump.z01.zip](https://github.com/Phobos-developers/Phobos/files/12284954/extcrashdump.z01.zip)
[extcrashdump.z02.zip](https://github.com/Phobos-developers/Phobos/files/12284956/extcrashdump.z02.zip)
[extcrashdump.z03.zip](https://github.com/Phobos-developers/Phobos/files/12284957/extcrashdump.z03.zip)
[extcrashdump.z04.zip](https://github.com/Phobos-developers/Phobos/files/12284960/extcrashdump.z04.zip)
[extcrashdump.z05.zip](https://github.com/Phobos-developers/Phobos/files/12284946/extcrashdump.z05.zip)

**Comment by TaranDahl** [comment]
This seems caused by the button "存档功能修复" in mental omega. I turn this button off and don't get this crash anymore.
The "存档功能修复" button is said to fix the problem of the corruption of "BuildOffAlly" and map light tint after loading. Given that in build 35 Phobos added a bug-fix of light tint corruption after loading, I guess there may be some conflicts and cause this crash.

**Comment by HyperionFrog** [comment]
> This seems caused by the button "存档功能修复" in mental omega. I turn this button off and don't get this crash anymore. The "存档功能修复" button is said to fix the problem of the corruption of "BuildOffAlly" and map light tint after loading. Given that in build 35 Phobos added a bug-fix of light tint corruption after loading, I guess there may be some conflicts and cause this crash.

Pretty accurate location of the bug. It's related to a commit in build 32. I've made a PR [#1220](https://github.com/Phobos-developers/Phobos/pull/1220).

**Comment by chaserli** [comment]
> Pretty accurate location of the bug. It's related to a commit in build 35. I've made a PR [#1220](https://github.com/Phobos-developers/Phobos/pull/1220).

According to @HyperionFrog 's report, the latest commit c1fb1d93e48fbd581fdd86978badf5ff60525d41 should have fixed this unreproducible issue. 

Whether it's true or not we won't keep track of this
