### ISSUE TITLE
"OpenTopped=" cannot be properly inherited in "Convert.From"->"Convert.To"

### ISSUE THREAD

**Issue by Zhcs0712** [Phobos-developers/Phobos#1110]
### Description

"OpenTopped=" cannot be properly inherited in "Convert.From"->"Convert.To".
In the following INI code, the INF in VehicleB still can't fire.But if VehicleA's OpenTopped=yes, INF can fire.

### Phobos Version

b36

### INI code

```ini
[VehicleA]
...
InitialPayload.Types=INF
InitialPayload.Nums=1
OpenTopped=no

[VehicleB]
...
InitialPayload.Types=INF
InitialPayload.Nums=1
OpenTopped=yes

[SuperWeapon]
Convert.From=VehicleA
Convert.To=VehicleB
```

### Steps to reproduce

1.
2.
3.
...

### Expected behaviour

"OpenTopped=" can be properly inherited.
Whether VehicleA's OpenTopped=yes or no,The INF in VehicleB could fire.

### Actual behaviour

The INF in VehicleB couldn't fire.

### Checklist

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by Starkku** [comment]
This has been fixed in a5b0edd40b049aa960eb2297c246cd0b06653f2f.
