### ISSUE TITLE
Interceptor.WeaponReplaceProjectile vs Interceptable/Armor status

### ISSUE THREAD

**Issue by Speederovsky** [Phobos-developers/Phobos#1116]
### Description

Let's start with the design idea that reveals this issue: to have units that support others by enhancing their projectiles using  **Interceptor.WeaponOverride=**... and **Interceptor.WeaponReplaceProjectile=yes**.

If you make an object with a weapon that intercepts certain **friendly** projectiles to update their features and the new projectile has Interceptable=no set on it to prevent further interception of the already updated projectile, the _most common scenario_ is interceptor will continue to target this projectile regardless. 

The same happens if the new projectile has Armor that is not targetable by the friendly interceptor, it will still be targeted and fired upon. An **enemy** interceptor will also target it, but the projectile will not be detonated.

The interceptors will currently continue to target the already replaced projectiles until they are gone.

I wrote _"most common scenario"_ - so when does this not happen? It appears that if the already updated projectile is what enters a similar interceptor's weapon range, it will not be fired upon at all. My guess is that the interceptors only consider the status the projectile had the moment it was targeted by them.

### Phobos Version

Build 36

### Steps to reproduce

1. Make a friendly or enemy interceptor weapon that uses the following:
```
Interceptor.WeaponOverride=(weapon)
Interceptor.WeaponReplaceProjectile=yes
```
2. Make a projectile that definitely is and should be interceptable by it.
3. Make (weapon) use a new projectile with **Interceptable=no** or **Armor** that is not supposed to be targeted by the interceptor.
4. Intercept the projectile fired within the interceptor's weapon range to update it.
5. To reproduce the case when it doesn't happen, have the already updated projectile enter the range of another interceptor.

### Expected behaviour

The interceptor should stop targeting the replaced projectile.

### Actual behaviour

The replaced projectile is still being targeted by the interceptor.

### Checklist

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by Starkku** [comment]
Should be fixed in 1249ba71c61fb8f73a809b71c347e7496181d20b
