### ISSUE TITLE
AltPalette=yes fix causes animations to render black

### ISSUE THREAD

**Issue by mevitar** [Phobos-developers/Phobos#1119]
### Description

Animations with AltPalette=yes tag render black ever since the AltPalette=yes fixes and improvements branch. Tested with weather control superweapon, as the original clouds have AltPalette=yes.

### Phobos Version

https://github.com/Phobos-developers/Phobos/commit/9de73a600dae7a56aa1ce016684ee3ffab701c00

### Steps to reproduce

Fire the original Weather Control SW or something using the original cloud animations.

### Expected behaviour

Clouds render normally, with colors.

### Actual behaviour

Clouds render black.

### Checklist

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by mevitar** [comment]
Tested with AltPalette.ApplyLighting=yes, it appears to fix the issue. It will obviously tint the clouds but the animation will render properly. Adding UseNormalLight=yes will brighten the clouds if the map is dark, but they will still be tinted.

Without AltPalette.ApplyLighting=yes, the clouds are dark even with UseNormalLight=yes.

**Comment by Starkku** [comment]
This only happens if the game is launched without a spawner. Not sure why, will investigate.

**Comment by mevitar** [comment]
Fixed.
