### ISSUE TITLE
[Vanilla Bug] Make FireOnce=yes with deploy weapons work on other TechnoTypes

### ISSUE THREAD

**Issue by Danielovich7** [Phobos-developers/Phobos#112]
Currently, the tag "FireOnce=" only seems to work on InfantryTypes. It would be helpful to have it work on other TechnoTypes. For example, this could make vehicle using a deployable weapon exit their attack mmission once the weapon is fired.

**Comment by Thrifinesma** [comment]
It already works on all sorts of TechnoTypes

**Comment by Danielovich7** [comment]
Then maybe there's an interaction with another tag that prevent it from working, because it does not work for me.

**Comment by Falaka21** [comment]
It doesn't work for me,also.

**Comment by Thrifinesma** [comment]
![FireOnce](https://user-images.githubusercontent.com/45818100/114292527-a7d43500-9ac1-11eb-854a-e622e0b6b8f4.gif)
I set `FireOnce=yes` to M60 105mm Vulcan2, all work

**Comment by secsome** [comment]
Anyone can test it again?
