### ISSUE TITLE
Intercept proj leads to Reconnection Error

### ISSUE THREAD

**Issue by reedom114514** [Phobos-developers/Phobos#1123]
### Description

Self Explained in the title

### Phobos Version

Newest new AE pull request nightly build based on B36

### Conditions to reproduce

MO3, with rules change.

### INI code

```ini
[Any proj]
Interceptable=yes 
Armor=projlight

[Any Techno]
Primary=InterceptWeapon
Interceptor=yes
Interceptor.GuardRange=7
```

### Steps to reproduce

1. build your intercept carrier
2. push them forwards to enemy proj launcher in multi game
3. kabooooooooooooom!

### Expected behaviour

intercept and nothing happens as it is in single game

### Actual behaviour

kaboooooooooooooooooooom, LIKE I USE ESC IN ANY GAME

### Additional context

cannot provide since it is broken with ESC, I cannot pause to make video

### Checklist

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by chaserli** [comment]
probably fixed in b02a821 and #1255 ? if not then reopen
