### ISSUE TITLE
Force shield tint would penetrate shroud

### ISSUE THREAD

**Issue by reedom114514** [Phobos-developers/Phobos#1128]
### Description

Self-explained.

### Conditions to reproduce

See the force shield protected enemy building in some situation.
What about mine? Using nightly build to play MO3 mission, one of them has many many force shield in shroud

### INI code

```ini
The same as what it is in vanilla YR, expect Protect.PowerOutage=0 things.
```

### Steps to reproduce

1. Watching force shield casted by AI in shroud
2. Looking into the shroud
3. What a beautiful blue

### Expected behaviour

I can see blue building outside the shroud, but I cannot see what I should not see.

### Actual behaviour

What a beautiful blue in shroud

### Additional context

![shroud force](https://github.com/Phobos-developers/Phobos/assets/117975708/350155a1-c29e-45a3-b9fb-69e43b99ba98)

### Checklist

- [X] The issue is not introduced by Phobos or any other engine extension, such as Ares, Kratos etc.
- [X] The issue wasn't fixed in the most recent version of Ares/Phobos yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by Starkku** [comment]
As an additional information, this issue only applies to voxel turrets (and only the turrets) on buildings.

**Comment by chaserli** [comment]
This issue wasn't introduced until b41, so I assume the "nightly build" you referred to was #826 back in 2023
