### ISSUE TITLE
Tag BuildingType>PlacementPreview cannot work

### ISSUE THREAD

**Issue by reedom114514** [Phobos-developers/Phobos#1129]
### Description

This tag is for buildings which we do not want to show the preview, I have used it on plugs, however, it cannot work well.

### Phobos Version

nightly build b36

### Conditions to reproduce

Write the PlacementPreview=no or false in the [plug] techno.

### INI code

```ini
PlacementPreview=no
```

### Steps to reproduce

1. building
2. construction complete

### Expected behaviour

No preview here.

### Actual behaviour

Oops, it has one.

### Additional context

![Cache_-bfe80ce22086c16](https://github.com/Phobos-developers/Phobos/assets/117975708/1956019b-cddf-43c9-8c76-9050cf9bd527)

### Checklist

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by Starkku** [comment]
Should be fixed in 2c91fe1.

**Comment by reedom114514** [comment]
Thank you! It got fixed.
