### ISSUE TITLE
Ares' AttachedSystem= tag ceased to work

### ISSUE THREAD

**Issue by mevitar** [Phobos-developers/Phobos#1136]
### Description

Attaching particle trailers to projectiles through Ares' AttachedSystem= flag does not work in the (currently) newest devbuild. It worked fine just few builds earlier.

### Phobos Version

https://github.com/Phobos-developers/Phobos/commit/f2317312ef8119791f4bd4b38acd10859f99309e

### Steps to reproduce

1. Add AttachedSystem= to a projectile.

### Expected behaviour

The attached particle system should work properly.

### Actual behaviour

The attached particle system doesn't work unless an older Phobos build is used.

### Checklist

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by Speederovsky** [comment]
Same here.

**Comment by Belonit** [comment]
Should be fixed in 905c632

**Comment by mevitar** [comment]
Fixed.
