### ISSUE TITLE
New AI anti-air script cannot target air units owned by players

### ISSUE THREAD

**Issue by reedom114514** [Phobos-developers/Phobos#1156]
### Description

Now we have new AI AA script, after testing we find it is good in computer versus computer, though there is another issue that the AA air units would get close to each other, that is not bad.
But, the AA script would ignore players' aircraft, that is bad, this means we cannot get a better AI that would act better in anti players' air spamming.

### Phobos Version

B36

### Conditions to reproduce

vanilla MO3 with some phobos rules

### INI code

```ini
Self explained
```

### Steps to reproduce

1. Building air units in the base
2. See what happens among computers

### Expected behaviour

Computers would send AA units to destroy me airforces.

### Actual behaviour

No, instead, they put their units that would trans into my airforces' exp.

### Checklist

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by Starkku** [comment]
This is not acceptable amount of information provided for bug/issue report.

1. Which script action/team mission is the 'new AI AA script' exactly?
2. This script action ignores player's aircraft *how*? It does not target enemy house AircraftTypes or what?

**Comment by reedom114514** [comment]
> This is not acceptable amount of information provided for bug/issue report.
> 
> 1. Which script action/team mission is the 'new AI AA script' exactly?
> 2. This script action ignores player's aircraft _how_? It does not target enemy house AircraftTypes or what?
1.
16 patrol-10000 "Target Type#", search and destroy the air units-17 change the script
But in the battle, the script is stopped at 10000.
2.
Not only air units, but also all the things, 10000 can scan the AI controlled units, but it cannot scan my units (AI vs AI is okay, AI vs ME is not)

**Comment by reedom114514** [comment]
Never seen this in B45
