### ISSUE TITLE
Spy causes error in RA2 mode

### ISSUE THREAD

**Issue by CCCP84** [Phobos-developers/Phobos#1158]
### Description

In RA2 mode the error occurs the moment when enemy spy comes into view on the screen.

### Phobos Version

[b5ec570](https://github.com/Phobos-developers/Phobos/commit/b5ec570a9f1d016d500398312034cb6a38d7078d)

### Conditions to reproduce

RA2 mode

### Steps to reproduce

1. Move the screen to an enemy spy.
It does not matter whether the area is visible or whether it is a black, unexplored area.

### Expected behaviour

Nothing happen )

### Actual behaviour

![SPY](https://github.com/Phobos-developers/Phobos/assets/144725555/72acac92-4b64-49bd-9267-74d77384c5e2)

[debug.log](https://github.com/Phobos-developers/Phobos/files/12599333/debug.log)
[except.txt](https://github.com/Phobos-developers/Phobos/files/12599334/except.txt)
[syringe.log](https://github.com/Phobos-developers/Phobos/files/12599338/syringe.log)
[debug.log](https://github.com/Phobos-developers/Phobos/files/12599347/debug.log)
[debug.20230913-171740.log](https://github.com/Phobos-developers/Phobos/files/12599348/debug.20230913-171740.log)

### Checklist

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by Metadorius** [comment]
This is not sufficient to determine the cause of the issue.
1. "last" phobos version does not exist. Please hover over the `Phobos.dll` and see what version is there.
2. Please read the error message and upload whatever it says here, so we can actually investigate.
Also you clearly haven't read the checklist. This is not your typical "license agreement", so please spend 5 minutes to actually read and fulfill what is asked there before checking.

**Comment by Metadorius** [comment]
More so, why do you think it's the Phobos causing an issue? `RA2Mode` doesn't exist in Phobos whatsoever, it's in the CnCNet spawner that was rewritten by @Belonit. Have you tried deleting Phobos from beta and replicating the issue?

**Comment by CCCP84** [comment]
Yes. Without Phobos the problem disappears.

**Comment by CCCP84** [comment]
> This is not sufficient to determine the cause of the issue.
> 
> 1. "last" phobos version does not exist. Please hover over the `Phobos.dll` and see what version is there.
> 2. Please read the error message and upload whatever it says here, so we can actually investigate.
> 
> Also you clearly haven't read the checklist. This is not your typical "license agreement", so please spend 5 minutes to actually read and fulfill what is asked there before checking.



> This is not sufficient to determine the cause of the issue.
> 
> 1. "last" phobos version does not exist. Please hover over the `Phobos.dll` and see what version is there.
> 2. Please read the error message and upload whatever it says here, so we can actually investigate.
> 
> Also you clearly haven't read the checklist. This is not your typical "license agreement", so please spend 5 minutes to actually read and fulfill what is asked there before checking.

Done

**Comment by CCCP84** [comment]
I figured out what the reason was. I used Phobos.dll that Starkku sent me. The version number indicated there is the same, but the size is different. With this file, the spy is disguised as Initiate by default, rather than as a conscript. This causes an error in the RA2 mode.

**Comment by Metadorius** [comment]
Commit 6140343de63803f66a47a38f8cf2c886b84e6e22 may've fixed it, can you download the latest nightly build off develop and confirm whether the issue was fixed or not?

**Comment by CCCP84** [comment]
> Commit [6140343](https://github.com/Phobos-developers/Phobos/commit/6140343de63803f66a47a38f8cf2c886b84e6e22) may've fixed it, can you download the latest nightly build off develop and confirm whether the issue was fixed or not?

i checked. now all works good.
no errors.
