### ISSUE TITLE
Fix AlternateFLH "Fix"

### ISSUE THREAD

**Issue by Artizy2333** [Phobos-developers/Phobos#1224]
### Description

I think the vehicle code AlternateFLH in the vehicle is not entirely a bug. It can be used to create many interesting effects. Can you add a switch to control whether it is "fixed"?

### Steps to reproduce

don't need

### Expected behaviour

don't need

### Actual behaviour

don't need

### Checklist

- [X] The issue is not introduced by Phobos or any other engine extension, such as Ares, Kratos etc.
- [X] The issue wasn't fixed in the most recent version of Ares/Phobos yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by DeathFishAtEase** [comment]
This is a valuable Issue, and it indeed has many modders who will use this feature in their mods.
The existing Phobos fix for them is just a change from one hardcoded rule to another.
Previously, someone jokingly said that this was a hardcoded behavior "introduced" by Phobos and should be "dehardcoded" :P
