### ISSUE TITLE
Veinhole Using

### ISSUE THREAD

**Issue by KuroNoSeiHai** [Phobos-developers/Phobos#1249]
### Description

It can't work. 

### Phobos Version

Build 39

### Steps to reproduce

1.I copied TS ini and SHP(.tem .sno) file. 
2.And I use Map editor added Veinhole(Overlay)
3.Test

### Expected behaviour

Works like TS.

### Actual behaviour

Just like a normal terrain.

### Checklist

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by ZivDero** [comment]
What map editor did you use? FA2 by default does not place Veinholes correctly, you need to set some data (please refer to FS or WAE to do it correctly). If that doesn't help, please provide all your code. Also keep in mind you have to pre-place some veins for them to grow at all IIRC.

**Comment by KuroNoSeiHai** [comment]
> What map editor did you use? FA2 by default does not place Veinholes correctly, you need to set some data (please refer to FS or WAE to do it correctly). If that doesn't help, please provide all your code. Also keep in mind you have to pre-place some veins for them to grow at all IIRC.

I am using FA2. How to set FA2 to place Veinholes correctly?

**Comment by KuroNoSeiHai** [comment]
> What map editor did you use? FA2 by default does not place Veinholes correctly, you need to set some data (please refer to FS or WAE to do it correctly). If that doesn't help, please provide all your code. Also keep in mind you have to pre-place some veins for them to grow at all IIRC.

I am using FA2. OK, I will try to WAE.

**Comment by KuroNoSeiHai** [comment]
> What map editor did you use? FA2 by default does not place Veinholes correctly, you need to set some data (please refer to FS or WAE to do it correctly). If that doesn't help, please provide all your code. Also keep in mind you have to pre-place some veins for them to grow at all IIRC.

I used WAE to place Veinholes. But it still doesn't work. Here is my code.
[rulesmd.txt](https://github.com/Phobos-developers/Phobos/files/15124813/rulesmd.txt)

And I don't know how to use WAE to place veins.

**Comment by ZivDero** [comment]
> > What map editor did you use? FA2 by default does not place Veinholes correctly, you need to set some data (please refer to FS or WAE to do it correctly). If that doesn't help, please provide all your code. Also keep in mind you have to pre-place some veins for them to grow at all IIRC.
> 
> I used WAE to place Veinholes. But it still doesn't work. Here is my code. [rulesmd.txt](https://github.com/Phobos-developers/Phobos/files/15124813/rulesmd.txt)
> 
> And I don't know how to use WAE to place veins.

WAE has a special "Place Veinhole" tool, akin to the one found in FS. Please use that and don't forget to place veins around the veinhole.

**Comment by KuroNoSeiHai** [comment]
> > > What map editor did you use? FA2 by default does not place Veinholes correctly, you need to set some data (please refer to FS or WAE to do it correctly). If that doesn't help, please provide all your code. Also keep in mind you have to pre-place some veins for them to grow at all IIRC.
> > 
> > 
> > I used WAE to place Veinholes. But it still doesn't work. Here is my code. [rulesmd.txt](https://github.com/Phobos-developers/Phobos/files/15124813/rulesmd.txt)
> > And I don't know how to use WAE to place veins.
> 
> WAE has a special "Place Veinhole" tool, akin to the one found in FS. Please use that and don't forget to place veins around the veinhole.

I have used it. But it seems WAE YR can't place veins. I don't find it.

**Comment by KuroNoSeiHai** [comment]
> > > > > What map editor did you use? FA2 by default does not place Veinholes correctly, you need to set some data (please refer to FS or WAE to do it correctly). If that doesn't help, please provide all your code. Also keep in mind you have to pre-place some veins for them to grow at all IIRC.
> > > > 
> > > > 
> > > > I used WAE to place Veinholes. But it still doesn't work. Here is my code. [rulesmd.txt](https://github.com/Phobos-developers/Phobos/files/15124813/rulesmd.txt)
> > > > And I don't know how to use WAE to place veins.
> > > 
> > > 
> > > WAE has a special "Place Veinhole" tool, akin to the one found in FS. Please use that and don't forget to place veins around the veinhole.
> > 
> > 
> > I have used it. But it seems WAE YR can't place veins. I don't find it.
> 
> ![image](https://private-user-images.githubusercontent.com/5639388/325974476-33146dee-6439-4586-8bef-40facb539cec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzQ1MTksIm5iZiI6MTcxNDEzNDIxOSwicGF0aCI6Ii81NjM5Mzg4LzMyNTk3NDQ3Ni0zMzE0NmRlZS02NDM5LTQ1ODYtOGJlZi00MGZhY2I1MzljZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMTIyMzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODdhZjZiZWNjMGIzYjBjOWMzMDIyZWFjZTIzODlhMTAwMGQxNDNkZGM4YzgwMjc5ODNiYjQ0OWQ5NGE0ZjZkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pZ46MfGbIJlX8TiiSNMACFrKXDEJQPNHe6_pw9mpEK0)
> 
> I've attached a test map.
> 
> [veintest.txt](https://github.com/Phobos-developers/Phobos/files/15130576/veintest.txt)

Thanks, I will try it.

**Comment by KuroNoSeiHai** [comment]
> > > > > > What map editor did you use? FA2 by default does not place Veinholes correctly, you need to set some data (please refer to FS or WAE to do it correctly). If that doesn't help, please provide all your code. Also keep in mind you have to pre-place some veins for them to grow at all IIRC.
> > > > > 
> > > > > 
> > > > > I used WAE to place Veinholes. But it still doesn't work. Here is my code. [rulesmd.txt](https://github.com/Phobos-developers/Phobos/files/15124813/rulesmd.txt)
> > > > > And I don't know how to use WAE to place veins.
> > > > 
> > > > 
> > > > WAE has a special "Place Veinhole" tool, akin to the one found in FS. Please use that and don't forget to place veins around the veinhole.
> > > 
> > > 
> > > I have used it. But it seems WAE YR can't place veins. I don't find it.
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/5639388/325974476-33146dee-6439-4586-8bef-40facb539cec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzQ1MTksIm5iZiI6MTcxNDEzNDIxOSwicGF0aCI6Ii81NjM5Mzg4LzMyNTk3NDQ3Ni0zMzE0NmRlZS02NDM5LTQ1ODYtOGJlZi00MGZhY2I1MzljZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMTIyMzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODdhZjZiZWNjMGIzYjBjOWMzMDIyZWFjZTIzODlhMTAwMGQxNDNkZGM4YzgwMjc5ODNiYjQ0OWQ5NGE0ZjZkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pZ46MfGbIJlX8TiiSNMACFrKXDEJQPNHe6_pw9mpEK0)
> > I've attached a test map.
> > [veintest.txt](https://github.com/Phobos-developers/Phobos/files/15130576/veintest.txt)
> 
> Thanks, I will try it.
![image](https://github.com/Phobos-developers/Phobos/assets/46418809/deb5da4f-79a0-46c2-8233-f1c35d72b28b)
It seems something wrong.

**Comment by KuroNoSeiHai** [comment]
> > > > > What map editor did you use? FA2 by default does not place Veinholes correctly, you need to set some data (please refer to FS or WAE to do it correctly). If that doesn't help, please provide all your code. Also keep in mind you have to pre-place some veins for them to grow at all IIRC.
> > > > 
> > > > 
> > > > I used WAE to place Veinholes. But it still doesn't work. Here is my code. [rulesmd.txt](https://github.com/Phobos-developers/Phobos/files/15124813/rulesmd.txt)
> > > > And I don't know how to use WAE to place veins.
> > > 
> > > 
> > > WAE has a special "Place Veinhole" tool, akin to the one found in FS. Please use that and don't forget to place veins around the veinhole.
> > 
> > 
> > I have used it. But it seems WAE YR can't place veins. I don't find it.
> 
> ![image](https://private-user-images.githubusercontent.com/5639388/325974476-33146dee-6439-4586-8bef-40facb539cec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNDE5ODUsIm5iZiI6MTcxNDE0MTY4NSwicGF0aCI6Ii81NjM5Mzg4LzMyNTk3NDQ3Ni0zMzE0NmRlZS02NDM5LTQ1ODYtOGJlZi00MGZhY2I1MzljZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMTQyODA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGQ1ZGZkYWI3M2UzNzczZWVkYzc5ZDg0M2JjNDkzOWM3NWFmZjJkY2M3MjQ0MWExMGJiMTE4NTE4YWMxZTI2MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3V_tqfwZxLpSFICAs5NRVcJknDL6pVDUAR_fgTd26tQ)
> 
> I've attached a test map.
> 
> [veintest.txt](https://github.com/Phobos-developers/Phobos/files/15130576/veintest.txt)

Thanks, it works. But I find it must set 129=VEINS, 170=VEINHOLE and 181=VEINHOLEDUMMY in [OverlayTypes](rulesmd) like TS. If set like docs, it will not work.

**Comment by ZivDero** [comment]
> Thanks, it works. But I find it must set 129=VEINS, 170=VEINHOLE and 181=VEINHOLEDUMMY in [OverlayTypes](rulesmd) like TS. If set like docs, it will not work.  I mean use TS overlay indices in rulesmd rather than docs said and your text map can make it. But I don't know if this condition mean works properly.

The IDs *ARE* the same as in TS. The IDs provided in the docs should be correct and the same ones as in TS. Keep in mind that what matters is not the number left of "=", but the actual position in the list, 0-based. So if it says 126, it should be the 126th (or 127th 1-based) line.

**Comment by Metadorius** [comment]
> The IDs _ARE_ the same as in TS. The IDs provided in the docs should be correct and the same ones as in TS. Keep in mind that what matters is not the number left of "=", but the actual position in the list, 0-based. So if it says 126, it should be the 126th (or 127th 1-based) line.

I think this could be made more clear in docs and/or unhardcoded, because even I recall me not fully realizing that, so a reminder would be good since people might not remember all the engine quirks.

**Comment by KuroNoSeiHai** [comment]
> > Thanks, it works. But I find it must set 129=VEINS, 170=VEINHOLE and 181=VEINHOLEDUMMY in [OverlayTypes](rulesmd) like TS. If set like docs, it will not work.  I mean use TS overlay indices in rulesmd rather than docs said and your text map can make it. But I don't know if this condition mean works properly.
> 
> The IDs _ARE_ the same as in TS. The IDs provided in the docs should be correct and the same ones as in TS. Keep in mind that what matters is not the number left of "=", but the actual position in the list, 0-based. So if it says 126, it should be the 126th (or 127th 1-based) line. In fact, vanilla rules already have them in the correct place.

Thanks, like the animations list. I got it. OverlayTypes 39 next to 42, cause this.

**Comment by KuroNoSeiHai** [comment]
BTW, is there another method to create veinhole or veins, for example, use debris.

**Comment by KuroNoSeiHai** [comment]
Excuse me, now I can use WAE place veinhole. BUT I don't know how to place vein surrounding, because I can't find Veins. It is not in WAE overlay list.

**Comment by ZivDero** [comment]
> Excuse me, now I can use WAE place veinhole. BUT I don't know how to place vein surrounding, because I can't find Veins. It is not in WAE overlay list.

By default the VEINS is hidden in WAE. You need to remove the line `VEINS=true` from `EditorConfig.ini`.

**Comment by KuroNoSeiHai** [comment]
> > Excuse me, now I can use WAE place veinhole. BUT I don't know how to place vein surrounding, because I can't find Veins. It is not in WAE overlay list.
> 
> By default the VEINS overlay is hidden in WAE for YR. You need to remove the line `VEINS=true` from `EditorConfig.ini`.

I set it, and I can place VEINS. I meet another problem. I used FinalSun place Veinhole and veins, veins can grow properly, but I place in WAE, vein can't grow.
![image](https://github.com/Phobos-developers/Phobos/assets/46418809/a3f2d62b-31e6-4e5a-835c-9efb93ab7620)
This is screenshot, i place it.

**Comment by KuroNoSeiHai** [comment]
> > > Excuse me, now I can use WAE place veinhole. BUT I don't know how to place vein surrounding, because I can't find Veins. It is not in WAE overlay list.
> > 
> > 
> > By default the VEINS overlay is hidden in WAE for YR. You need to remove the line `VEINS=true` from `EditorConfig.ini`.
> 
> I set it, and I can place VEINS. I meet another problem. I used FinalSun place Veinhole and veins, veins can grow properly, but I place in WAE, vein can't grow. ![image](https://private-user-images.githubusercontent.com/46418809/326171764-a3f2d62b-31e6-4e5a-835c-9efb93ab7620.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0OTUzOTAsIm5iZiI6MTczMjQ5NTA5MCwicGF0aCI6Ii80NjQxODgwOS8zMjYxNzE3NjQtYTNmMmQ2MmItMzFlNi00ZTVhLTgzNWMtOWVmYjkzYWI3NjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAwMzgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MDMyOWFjYTAyZmEwZDBkZmVmZmEzMDc5NmE2OTlkMWIwYzNlMzc3YzRiMThiNzEzMmQzOGEwOTY4MjQxYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zWjwhGdJBf53DFxFmAjBWBQoo-NpbrJeVVWjiVY25do) This is screenshot, i place it.

Memos:
In maps [Basic] should have VeinGrowthEnabled=yes.
