### ISSUE TITLE
2 issues about Kit/Disguise

### ISSUE THREAD

**Issue by reedom114514** [Phobos-developers/Phobos#1268]
### Description

1 you cannot see your allies' mirage tank
2 some infs (ex. Saboteur in MO3, a kind of spy inf) become a strange blue shadow when paradropped, this might be the problem of infs paradrop rather than kitup though

### Phobos Version

b40/b41

### Conditions to reproduce

MO3.3.6 with old syringe

### INI code

```ini
Self explained
```

### Steps to reproduce

Building a mirage tank and call the other player to see it
Paradropping the spy

### Expected behaviour

shown as normal

### Actual behaviour

1 invisible
2 invisible, and strange blue shadows around

### Additional context

![image](https://github.com/Phobos-developers/Phobos/assets/117975708/e234ead2-e537-41aa-b0c2-02ef19930164)

### Checklist

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by chaserli** [comment]
set `DisguiseBlinkingVisibility` to team may solve it. It was drawing the conscript's paradrop frame with the sbtr's shp due to the discrepancy between IsAlliedWith wrapper and ControlledByCurrentPlayer wrapper in #653.

**Comment by reedom114514** [comment]
> set `DisguiseBlinkingVisibility` to team may solve it. It was drawing the conscript's paradrop frame with the sbtr's shp due to the discrepancy between IsAlliedWith wrapper and ControlledByCurrentPlayer wrapper in #653.

Confirmed, it works, THX!

**Comment by Metadorius** [comment]
I am not sure this should be closed. Per my understanding the default behavior was broken?

**Comment by chaserli** [comment]
> I am not sure this should be closed. Per my understanding the default behavior was broken?

It is indeed incoherent

**Comment by FS-21** [comment]
> `DisguiseBlinkingVisibility`

Since the existence of DisguiseBlinkingVisibility the vanilla behaviour is broken and you have to add that tag with owner,allies (not at home so I don't know if I spelled it right) for fix the broken behaviour.

**Comment by Starkku** [comment]
Should be fixed in 5dc91bad6e40709777489ab09a5dac2e02b1134d
