### ISSUE TITLE
Issue about Harvester Counter

### ISSUE THREAD

**Issue by Ich-Henker** [Phobos-developers/Phobos#128]
Hi and thank you for developing this fantastic engine extension!

I found an issue with the harvester counter - when using the Ares Killing Drivers and Driver feature:

When an Infantry unit that is controlled by the player takes control of an enemy harvester wich driver has been killed the harvester counter detects that as having one more maximum miner but not increases the actual miner counter itself  - so 2/3 harvesters becomes 2/4 harvesters.

**Comment by Thrifinesma** [comment]
Does this enemy harvester Dock= contain your refinery?

**Comment by Ich-Henker** [comment]
I checked: it happens even when I force fire my own harvesters and retake them with a driver=yes unit. After retaking them I have to manually send them harvesting again, they do not start on their own. 
But if I send them back to a refinery the counter is accurate again!
Sorry for not seeing that earlier.

Am 2. April 2021 18:20:40 MESZ schrieb Uranusian ***@***.***>:
>Does this enemy harvester Dock= contain your refinery?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Phobos-developers/Phobos/issues/128#issuecomment-812599899

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Thrifinesma** [comment]
> I checked: it happens even when I force fire my own harvesters and retake them with a driver=yes unit. After retaking them I have to manually send them harvesting again, they do not start on their own. But if I send them back to a refinery the counter is accurate again! Sorry for not seeing that earlier. This then is more of an Ares issue where killed driver ahrvesters do not automatically start harvesting. Am 2. April 2021 18:20:40 MESZ schrieb Uranusian ***@***.***>:
> […](#)
> Does this enemy harvester Dock= contain your refinery? -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#128 (comment)](https://github.com/Phobos-developers/Phobos/issues/128#issuecomment-812599899)
> -- Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

No matter. Thanks for your reporting
