### ISSUE TITLE
Custom radiation does not read custom InfDeathAnim and versus.armor tags.

### ISSUE THREAD

**Issue by silentrzk** [Phobos-developers/Phobos#1284]
### Description

![image](https://github.com/Phobos-developers/Phobos/assets/173544238/c367874e-25f9-498a-bb3a-15c78e56b67f)
Everything as the title says. Custom InfDeathAnim and versus.armor tags does not work with the custom radiation warhead. If I remember correctly, it worked on the previous dev build but I can't remember which build was it as I was away for several months and I just came back from modding again and downloaded the latest build, which somehow this bug occurs.

### Phobos Version

Dev Build 42

### Conditions to reproduce

Just normal INI code.

### INI code

```ini
[ToxinRadiation]
RadDurationMultiple=1           ; int
RadApplicationDelay=16          ; int
RadApplicationDelay.Building=0  ; int
RadLevelMax=500                 ; int
RadLevelDelay=90                ; int
RadLightDelay=90                ; int
RadLevelFactor=0.2              ; double
RadLightFactor=0.1              ; double
RadTintFactor=1.0               ; double
RadColor=0,255,0                ; RGB
RadSiteWarhead=ToxinSite        ; WarheadType
RadHasOwner=true
RadHasInvoker=true

[ToxinSite]
Verses=120%,120%,120%,35%,20%,20%,0%,0%,0%,100%,100%
Versus.venom=0%
;InfDeath=7
InfDeathAnim=TOXINDIE
Radiation=yes

[BlightBomb]
Damage=180
ROF=10
Range=6
Projectile=FighterBomb
Speed=100
Warhead=BlightBombWH
Report=KirovAttack
RadType=ToxinRadiation
RadLevel=200
Burst=1
```

### Steps to reproduce

1. Just copy the INI code. Nothing much to reproduce.
2.
3.
...

### Expected behaviour

InfDeathAnim should be the customized InfDeathAnim and the unit with custom armor should not get damaged.

### Actual behaviour

InfDeathAnim will still use InfDeath=7 and the unit with custom armor with its armored is equivalent to 0% on custom radiation's warhead will still get damaged instead of not getting damaged at all.

### Checklist

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by Starkku** [comment]
You most likely didn't add `ToxinSite` to `[Warheads]` list so it is actually using the default radiation Warhead here. Unlikely to be a Phobos bug, check and confirm here.

**Comment by silentrzk** [comment]
> You most likely didn't add `ToxinSite` to `[Warheads]` list so it is actually using the default radiation Warhead here. Unlikely to be a Phobos bug, check and confirm here.

Actually, it's there but I noticed it that there is another warhead that shares the same number. Thank you for your reply and I apologize for my carelessness.
