### ISSUE TITLE
Weird bug that audio emitting low quality sound.

### ISSUE THREAD

**Issue by silentrzk** [Phobos-developers/Phobos#1289]
### Description

A weird bug that the unit's voice was producing low quality audio(Deep voice and in slow motion) which the cause is by using attack and decay sounds. However, the voice's quality is normal as intended if I do not use attack and decay.

I have tried several attempts such as renaming the .wav files, decreasing the number of attack/decay/voice audios on the Sounds tag.

### Conditions to reproduce

Unfortunately, I am not sure how to reproduce this bug because it was random as I have never experienced this kind of issue before.

### INI code

```ini
[BMIGMove]
Sounds= gradio1a gradio1b gradio1c gradio1d gradio1e gradio1f gradio1g $vbmgmoa $vbmgmob $vbmgmoc $vbmgmod $vbmgmoe gradio3a gradio3b gradio3c gradio3d gradio3e gradio3f gradio3g 
Control= random attack decay
Attack=7
Decay=7
Volume=90
```

### Steps to reproduce

1. Nothing. Just copy any existing aircraft sound code and replace it with your own custom voices.
2.
3.
...

### Expected behaviour

The sound quality should be the same as from the original .wav file. With using the attack and decay sounds just like any normal aircraft voices.

### Actual behaviour

Low quality output(Deep voice and in slow motion) if I use the attack and decay sounds.

### Additional context

https://github.com/Phobos-developers/Phobos/assets/173544238/de9f938f-f6d9-4a9c-a476-dd2920927e45

[audio bug.zip](https://github.com/user-attachments/files/15945721/audio.bug.zip)

Inside the .zip file, it contains the .wav files that cause the bug. I have used different sounds with using attack and decay, but they worked as intended. However, I'd still like to find a way to solve this issue to avoid encountering this complicated bug and of course I want to use those voices in my mod.

### Checklist

- [X] The issue is not introduced by Phobos or any other engine extension, such as Ares, Kratos etc.
- [X] The issue wasn't fixed in the most recent version of Ares/Phobos yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by Starkku** [comment]
This appears to be a quirk of the audio engine, it will play any listed `Sounds` using the sampling rate/frequency of the first sample. Your new sounds are 48000hz and vanilla game's radio sounds are 22050hz. Because `gradio1X` will always be the first sound played, it will play the rest using same frequency, resulting in slowed-down playback.

Use same sampling rate across all listed sounds for a single event. Not really a bug but an engine limitation.
