### ISSUE TITLE
B42 version multiplayer online battle pop-up

### ISSUE THREAD

**Issue by 285984303** [Phobos-developers/Phobos#1290]
### Description

B42 version multiplayer online battle pop-up

### Steps to reproduce

B42 version multiplayer online battle pop-up

### Expected behaviour

B42 version multiplayer online battle pop-up

### Actual behaviour

![2099264e9ddd577491fe4012081ebdec](https://github.com/Phobos-developers/Phobos/assets/3397070/88925f29-3306-4e5c-a885-df467af7c42a)
[snapshot-20240624-202810.zip](https://github.com/user-attachments/files/15956504/snapshot-20240624-202810.zip)

### Checklist

- [X] The issue is not introduced by Phobos or any other engine extension, such as Ares, Kratos etc.
- [X] The issue wasn't fixed in the most recent version of Ares/Phobos yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by chaserli** [comment]
We are aware that MP issues are present. However I couldn't extract useful info from what you've provided
