### ISSUE TITLE
Fatal Error in multiplayer when DEP enabled with Build 42

### ISSUE THREAD

**Issue by VCStardust** [Phobos-developers/Phobos#1298]
### Description

If turn on DEP for all programs and services, multiplayer game will get Fatal Error in a few minutes.
If only turn on DEP for Windows programs and services, or add gamemd.exe to except, game will work normally.

### Phobos Version

Dev Build 42

### Conditions to reproduce

Turn on DEP for all programs and services.
Play multiplayer a few minutes.

### Steps to reproduce

1. Turn on DEP for all programs
2. Play multiplayer
3. Get Fatal Error in a few minutes

### Expected behaviour

Game works normally

### Actual behaviour

Get Fatal Error in a few minutes.

### Additional context

```
CONTEXT:  (.ecxr)
eax=1f1356f4 ebx=30532f40 ecx=39579640 edx=00000000 esi=31997e80 edi=00000000
eip=7980133c esp=0019d0e0 ebp=00000000 iopl=0         nv up ei pl nz na po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210202
Phobos!old_empty_log:
7980133c c3              ret
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 7980133c (Phobos!old_empty_log)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 00000008
   Parameter[1]: 7980133c
Attempt to execute non-executable address 7980133c

PROCESS_NAME:  gamemd.exe

EXECUTE_ADDRESS: 7980133c

FAILED_INSTRUCTION_ADDRESS: 
Phobos!old_empty_log+0
7980133c c3              ret

ERROR_CODE: (NTSTATUS) 0xc0000005 - 0x%p            0x%p                    %s

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  00000008

EXCEPTION_PARAMETER2:  7980133c

STACK_TEXT:  
00000000 00000000     00000000 00000000 00000000 Phobos!old_empty_log


STACK_COMMAND:  ~0s; .ecxr ; kb

SYMBOL_NAME:  Phobos!old_empty_log+0

MODULE_NAME: Phobos

IMAGE_NAME:  Phobos.dll

FAILURE_BUCKET_ID:  SOFTWARE_NX_FAULT_CODE_c0000005_Phobos.dll!old_empty_log
```

### Checklist

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by chaserli** [comment]
plz try if 217533a fixed it

**Comment by VCStardust** [comment]
Nightly Build 3723 fixed it
