### ISSUE TITLE
Fire Super Weapon at specified location no longer fires at random locations

### ISSUE THREAD

**Issue by Rhosalth7** [Phobos-developers/Phobos#1443]
### Description

I been using just like how is described in the docs this action ''505,0,0,SWIndex,-2,-1,-1,A'' in order to get a couple of SW's to fire at random locations using a random delay event, now this no longer happens and no SW is being fired even if the random delay value is set to something low.

### Phobos Version

https://github.com/Phobos-developers/Phobos/releases/tag/build-45

### Conditions to reproduce

Create any trigger involving the action 505 using either the map editor or the client ini's and give it the event 51 with a value of 10 to fire it as soon as possible.

### INI code

```ini
[Actions]
IONCOMPLEXSTORM=1,505,0,0,18,-2,-1,-1,A
; 18 - Is a Lightning Storm SW

[Events]
IONCOMPLEXSTORM=1,51,0,10

[Tags]
IONSTORMCOMPLEX=2,IonStorm_Spawn_Trigger 1,IONCOMPLEXSTORM

[Triggers]
IONCOMPLEXSTORM=Neutral,<none>,IonStorm_Spawn_Trigger,0,1,1,1,0
```

### Steps to reproduce

1.Create trigger in either map or client ini
2.Create event 51 with action 505 with the values to randomly fire
3.Launch the game and wait for the trigger to fire
...

### Expected behaviour

The event would fire, but no action would take place.

### Actual behaviour

The event would fire and so does the action.

### Additional context

INI code is all that is needed to reproduce the bug.

### Checklist

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by Metadorius** [comment]
@handama @chaserli we determined that it was #1430 that caused that

**Comment by Rhosalth7** [comment]
I tested the nightly from https://github.com/Phobos-developers/Phobos/pull/1444 and the trigger works fine now.
