### ISSUE TITLE
DIY Unit Trailer Animation Location & Multiple Trailer Settings

### ISSUE THREAD

**Issue by Dr-Harbinger** [Phobos-developers/Phobos#146]
_Introduce DIY Unit Trailer Animation Location and Multiple Trailer Settings to Phobos_
This allows users to customize the location of trailer animation and to add multiple trailers to a unit.
```ini
[VehicleArt]> Trailerlocation=F,L,H  ; (integer) 

                          Traile2=      
			  Trailer2Seperation= 
			  Trailer2location=

			  ......
```

**Comment by ayylmaoRotE** [comment]
Issue https://github.com/Phobos-developers/Phobos/issues/9

**Comment by Thrifinesma** [comment]
Duplicate of #9
