### ISSUE TITLE
Confilt with other patchers when use random start postion.

### ISSUE THREAD

**Issue by hejiajun107** [Phobos-developers/Phobos#1483]
### Description

The lasted phobos version confict with another patch base on reshade when start the game with random(unset) start position.
The patch is as followed
https://bbs.ra2diy.com/forum.php?mod=viewthread&tid=17820&extra=page%3D1

### Phobos Version

b40

### Conditions to reproduce

Launch the game in cncnet client and don't set the start position.

### Steps to reproduce

Launch the game in cncnet client and don't set the start position.

### Expected behaviour

No fatal error

### Actual behaviour

A fatal error  Exception code: C0000005 at 005D6C21

### Additional context

Please refer to the dump file
[dump file](https://1drv.ms/u/c/b55fc513e65d995c/EeQToLXrwMtDpIsqK4So1xMBZqm2kCKf_5cz3HthAKS5cw?e=gWd9Bu)

### Checklist

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by hejiajun107** [comment]
Maybe this description is not exactly ,i cannot Reproduce this any more. Maybe caused by other reasons

**Comment by Metadorius** [comment]
Let's close it then for now, if you come up with a reproduction scenario - you can reopen it once again.
