### ISSUE TITLE
Customizable Bounty Logic

### ISSUE THREAD

**Issue by yamanekoayf** [Phobos-developers/Phobos#15]
In light of a recent question raised in the channel,
I come up with this request for some further customization on Ares Bounty Logic in hope of enriching the feature's interactiveness while still respecting the original `Bounty.Value=` tag.

 `[TechnoType]►Bounty.Multiplier=` (float - multiplier)
The amount rewarded as bounty for this type is multiplied by this value to either increase, decrease, or nullify the effect. 
Support values range from -1.0 to reverse the effect to 1.0 to not apply the effect. 0.0 nullifies the bonus. Defaults to 1.0. 

Expected use-case of a negative value would be applying such logic on some mercenary units player can hire mid-game and have to pay for their services.

**Comment by Metadorius** [comment]
Should be directed to AlexB.
