### ISSUE TITLE
[New Feature] Make random starts truly random from cold boot

### ISSUE THREAD

**Issue by MRMIdAS** [Phobos-developers/Phobos#154]
Most noticible on maps you've selected before, from a cold boot. Fire up, say Bay Of Pigs. Play a game and quit. Now, boot back into the game, and as long as you don't select another map, every time you boot into the game and play Bay Of Pigs, you'll *ALWAYS* start in the same place if you have everyone set to random starts.

This obviously shouldn't happen, Countries are selected at random properly, so there is an RNG element that can randomise things, it just doesn't work for start locations.

(Yes, I know, no such thing as true RNG, blah blah blah)

Steps to Reproduce.
1)play game on map.
2)quit YR
3)Boot YR
4)Single Player>Skirmish
5)set alliances, colours, hell, even countries, just don't touch start location
6)start game.
Every time you repeat those steps, you'll *ALWAYS* spawn in the same location.

**Comment by Thrifinesma** [comment]
Have you tested the behavior in XNAClient?

**Comment by MRMIdAS** [comment]
I haven't as I don't use it. Behaviour occurs with ARES/PHOBOS though.

**Comment by Thrifinesma** [comment]
Alright, nowadays most mods are using XNAClient, which handled all game-starting related stuff. For example, Ares' `RandomSelectionWeight` will not work. So, to do such a feature almost equals to useless work. But eh, I'll (or we'll) consider it.

**Comment by MRMIdAS** [comment]
Fair enough. Personally, I've got no real need for it, (the client) so yeah, if it's a ballache, don't bother, but it'd be nice to have regardless.

**Comment by secsome** [comment]
Just use the Client is enough. No need for us to fix it.
