### ISSUE TITLE
[Vanilla Bug] Fix UI building placement bug

### ISSUE THREAD

**Issue by CatTanker** [Phobos-developers/Phobos#155]
There is a UI bug that occurs when a building (applies for main buildings and structures in both tabs) has been placed after clicking QWER but cannot be deployed in any of the chosen locations. if you click out and then attempt to use the QWER hotkeys again then you are unable to place the building without going to the sidebar and click on the cameo. 

The fix for this would allow the QWER hotkeys to be used after a failed building placement.
This would significantly benefit multiplayer games.

An example of this bug is below
https://user-images.githubusercontent.com/81521710/114013009-f9c95080-985e-11eb-849e-3a3512b27059.mp4

**Comment by Thrifinesma** [comment]
resolved in #287
