### ISSUE TITLE
Crashes and parsing errors

### ISSUE THREAD

**Issue by Ich-Henker** [Phobos-developers/Phobos#163]
Hey,
(is this the right place to post feature requests and ideas?)

Red Alert 2 has a harsh fatal error handling: it immediatly ends the round and shuts the game down. After years of modding other games and RA2 (e.g. Classic Doom) I do not see a reason or benefit in this harsh handling.

I would ask for removing the harsh crash handling by the game entirely or modifyng it in a creative way: maybe a string presented on screen or a debug entry or making the autoshutdown optional ...  One example:

The Game crashes when overlapping civilian buildings with occupants in them are destroyed. Given many custom made maps use overlapping buildings, eliminating this crash could make the game and modding and testing as a whole less frustrating - even some westwood maps have this problem e.g. Tanyas Playground.

Otherwise it would be benficial to enhance the parsing error detection which shows if you have an identifiable error:

Ares itself has a parsing error checker, 
AIEdit has a different type of checking for said errors, 
and aicheck is a very! useful.

If one could combine this error searching routines it would help a lot.

**Comment by secsome** [comment]
This feature is possibly impossible. So close it.
If anyone need some assistance on why the game crashed, press **OK** instead of **Cancel** and then upload the crashing snapshot folder. That will help us to find out what happened before your crash and might help you find out what is leading that.
