### ISSUE TITLE
Custom radiation crash

### ISSUE THREAD

**Issue by Ich-Henker** [Phobos-developers/Phobos#166]
Under which commit: Radiation Enhancement
Description: Using the [Demobomb] weapon with a rad level crashes the game on detonation. The Warhead is not the problem for it can be used via firing a non suicide projectile without radlevel set . Removing the RadLevel tag "solves" the problem.
Other files(optional):

[Demobomb]
Damage=300
ROF=80
Range=1
Projectile=InvisibleLow
Speed=35
RadLevel=100
Warhead=DemobombWH
Report=DemoTruckDie
Suicide=yes

**Comment by Metadorius** [comment]
Already fixed in the nightly. Please test it on the newest nightly build of the develop branch.

**Comment by Ich-Henker** [comment]
Sorry for not knowing instantly how to get that build, I searched around but couldn't find it - do you have a link?

**Comment by Metadorius** [comment]
It's on the main page of readme and docs. https://nightly.link/Phobos-developers/Phobos/blob/develop/.github/workflows/nightly.yml

**Comment by Ich-Henker** [comment]
Thank you!, 
the nightly build solved the issue; the radiation appears accordingly. Ssorry for not being informed about that fix before!
-A-

**Comment by Metadorius** [comment]
No worries, I'll release a new build soon which has those fixes included.
