### ISSUE TITLE
#Bug Report# DeployToBuilding & Shield

### ISSUE THREAD

**Issue by NetsuNegi** [Phobos-developers/Phobos#170]
When a unit with a shield is deployed as a building with a shield, the shield will be reset directly, regardless of whether the shield is damaged before deployment.

**Comment by TAK02** [comment]
How should the shield carry over? Absolutes? Ratio?

**Comment by Negi542554365** [comment]
> 盾牌应该如何结转？绝对吗 比率？

Returned to initial value

**Comment by Negi542554365** [comment]
> How should the shield carry over? Absolutes? Ratio?

That is to say, return to full directly

**Comment by Thrifinesma** [comment]
> How should the shield carry over? Absolutes? Ratio?

I think it should be ratio, since HP is so

**Comment by Negi542554365** [comment]
> 盾牌应该如何结转？绝对吗 比率？

I'm sorry I misunderstood you. The correct way is to inherit percentage
