### ISSUE TITLE
[Bug Report] Invalid shield interaction with unit-to-unit conversion

### ISSUE THREAD

**Issue by YinShuiCi** [Phobos-developers/Phobos#172]
Hi, my friend, I found that on the Ares platform, there seems to be some problems in the operation of shield logic in units that use both deformation logic and shield logic

[SIREN]
IsSimpleDeployer=yes
Convert.Deploy=SIREN2
Cursor.Deploy=ModeII

[SIREN2]
IsSimpleDeployer=yes
Convert.Deploy=SIREN
Cursor.Deploy=ModeI
Shield.Strength=2400
Shield.Armor=s_capital
Shield.AbsorbOverDamage=no
Shield.SelfHealing=120
Shield.SelfHealing.Rate=0.1
Shield.Respawn=1200
Shield.Respawn.Rate=2
Shield.BracketDelta=0
Shield.IdleAnim=SIRENSHLD
Shield.BreakAnim=SIRENSHLD2
Shield.HitAnim=

When the unit is converted from modeI to modeII, the shield logic will operate normally. However, when the unit is converted from modeII to modeI, there seems to be a problem in the operation of the shield logic. What I understand is that the modeII state of the unit has a shield, while the modeI state of the unit has no shield. However, when the unit is converted from modeII to modeI, the animation of the shield will still be displayed But no shield health(but still have BracketDelta of shield). If I misunderstand the code, please give me some guidance, thank you.

  报错

**Comment by Metadorius** [comment]
I am afraid that we can't fix this issue at the moment, inter-library communication is impossible due to Ares being closed-source and it's developer being busy.

**Comment by YinShuiCi** [comment]
@Metadorius
My friend, what you and your team have done is very good. I understand what you mean. Now, I just point out a small problem that may exist in the shield logic. I thought it was a one-sided problem of Phobos, but it seems that it is not. Praise you and your team for their selfless dedication!
