### ISSUE TITLE
Ask questions about the color of HarvesterCounter

### ISSUE THREAD

**Issue by Cpj636** [Phobos-developers/Phobos#187]
I am not sure whether it is a bug or I misunderstood something.
The R,G,B setting for HarvesterCounter seems different from others. For example, when I set ToolTipColor = 125,0,125, it should be something close to purple, however, for the HarvesterCounter, it looks more close to pink.
![image](https://user-images.githubusercontent.com/80351894/115682602-367d6780-a388-11eb-97ce-09fdae183382.png)
![image](https://user-images.githubusercontent.com/80351894/115683096-b0155580-a388-11eb-8c03-6759c4fc8b28.png)
Same thing also happens for Sidebar.HarvesterCounter.ColorYellow/Red. Except for 255,0,0 and 255,255,0, others all have a certain color difference in game. 
Is this problems caused by some additional settings I missed? Or does it relates to some other settings in Ares or the original game? 
Thanks for your review.

**Comment by TAK02** [comment]
Something's wrong on your end.
```[Nod]
;;Phobos-only flags
Sidebar.HarvesterCounter.ColorYellow=125,0,125
Sidebar.HarvesterCounter.ColorRed=255,0,255``` makes the counter go purple then magenta for Soviets.
```[GDI]
;;Phobos-only flags
Sidebar.HarvesterCounter.ColorYellow=0,125,125 ; R,G,B
Sidebar.HarvesterCounter.ColorRed=0,255,255``` makes the counter go teal/dark cyan then cyan for Allies.
