### ISSUE TITLE
Custom AI based on Gametype

### ISSUE THREAD

**Issue by MRMIdAS** [Phobos-developers/Phobos#20]
Would it be possible to have the game load a separate AI file based on Gametype? so in your "MPXX.ini" you have "AIFile=" which overrides the standard AI and makes it load the new one. It'd make Unholy Alliance playable against computer players possible without cloning buildings, which would be nice.

**Comment by Metadorius** [comment]
I am not sure if it's work for Phobos or perhaps this could be done better with CnCNet client.

**Comment by FS-21** [comment]
You can set [AITriggerTypes] and [AITriggerTypesEnable] in CnCNet client game mode INI files so you can have one Aimd.ini with every trigger and filter (enable/disable) and/or increase AI probabilities in the respective game modes.

**Comment by Thrifinesma** [comment]
As FS-21 said, set this to Client is a better and easier way
