### ISSUE TITLE
[Phobos bug] Shield logic and Verses

### ISSUE THREAD

**Issue by YLanlan** [Phobos-developers/Phobos#204]
If Verses≥100%
When the warhead hits the shield, it will directly damage the body

Examples：
![GIF 2021-4-27 12-29-37](https://user-images.githubusercontent.com/82437575/116848943-4b77b780-ac20-11eb-8047-d979d1edba8c.gif)

**Comment by Metadorius** [comment]
![image](https://user-images.githubusercontent.com/17500545/116861629-0fd2f280-ac0c-11eb-8fa4-795ee6018366.png)
Why do all users seem to have problems with the templates we made? Is it so hard to write bug reports according to the template?

**Comment by YLanlan** [comment]
> ![图像](https://user-images.githubusercontent.com/17500545/116861629-0fd2f280-ac0c-11eb-8fa4-795ee6018366.png)
> 为什么所有用户似乎都对我们制作的模板有疑问？根据模板编写错误报告是否如此困难？

I'm very sorry for the trouble.
I'll pay attention next time

**Comment by Thrifinesma** [comment]
> > ![图像](https://user-images.githubusercontent.com/17500545/116861629-0fd2f280-ac0c-11eb-8fa4-795ee6018366.png)
> > 为什么所有用户似乎都对我们制作的模板有疑问？根据模板编写错误报告是否如此困难？
> 
> I'm very sorry for the trouble.
> I'll pay attention next time

下次请准确描述问题，我试了好久才知道你说的是对单位本体的护甲大于等于100%才会有bug

**Comment by YLanlan** [comment]
> > > ![图像](https://user-images.githubusercontent.com/17500545/116861629-0fd2f280-ac0c-11eb-8fa4-795ee6018366.png)
> > > 为什么所有用户似乎都对我们制作的模板有疑问？根据模板编写错误报告是否如此困难？
> > 
> > 
> > 很抱歉给您带来麻烦。
> > 下次我会注意的
> 
> 下次请准确描述问题，我试了好久才知道你说的是对单位本体的护甲大于等于100％才会有bug
> 翻译：下次，请准确描述问题。我花了很长时间才发现您说的是该装甲本身的装甲大于或等于100％会导致该错误。

OK, I'm very sorry for the trouble
