### ISSUE TITLE
[Phobos Bug] Shield anim combined with Lightning Storm sometime result in a crash

### ISSUE THREAD

**Issue by Metadorius** [Phobos-developers/Phobos#209]
### Description:

When the Lightning storm hits and some shielded unit with an anim cloaks or uncloaks the game may crash. Suspect is the lighting change during an anim initialization but so far the only constantly reproducable crash is with LS. PsyDom also crashed for @Damfoos.

### Phobos Build:

[Nightly Build 57d62fe](https://github.com/Phobos-developers/Phobos/suites/2734002842/artifacts/60363493)

### Conditions:

Ares 3.0 installed; one of thefollowing INI settings is present on a shield anim:
```ini
[SHIELDANIMNAME]
UseNormalLight=yes
Normalized=yes
```

### Steps To Reproduce:

1. Have some unit with a shield animation constantly being stealthed and unstealthed. The more units - the more chance it will crash.
2. Create a Lightning Storm.
3. If it doesn't crash, repeat step 2 until crashes.

### Expected Behaviour:

The game functions as normal.

### Actual Behaviour:

The game crashes with a fatal error.

### Additional Files / Links:

[Damfoos' LS and PsyDom crash dumps](https://drive.google.com/drive/folders/1q0YrhzSct_AQFw-oISHx_vSgJ0hkguoN?usp=sharing)

**Comment by Metadorius** [comment]
![image](https://user-images.githubusercontent.com/17500545/118479195-66b2ee80-b719-11eb-8693-cf7366b89a73.png)
![image](https://user-images.githubusercontent.com/17500545/118479220-6d416600-b719-11eb-948c-6fa9b4df9aff.png)

**Comment by Belonit** [comment]
I can also confirm a crash for Ares 0.8. Tomorrow I will continue my research
