### ISSUE TITLE
Negative Designator

### ISSUE THREAD

**Issue by deathreaperz** [Phobos-developers/Phobos#21]
Since Designators can only be used on Self and Ally, to improve gameplay I suggest these:

[SuperWeapon]►SW.NegDesignators= (list of TechnoTypes)
List of enemy units and structures eligible for designating the target location. An empty list requires no negative designator. Defaults to none.
[SuperWeapon]►SW.AnyNegDesignator= (boolean)
Whether any enemy unit or structure is considered a valid negative designator for this super weapon. Overrides SW.NegDesignators. Defaults to no.
The negative designator range can be customized for each TechnoType individually.

[TechnoType]►NegDesignatorRange= (integer - cells)
Range in cells around the enemy unit or structure that becomes targetable by super weapons requiring this object as negative designator. Defaults to [TechnoType]►Sight.

Example:
[RadarJammerSpecial]
...
SW.NegDesignators=GAAIRC,NARADR
...

[GAAIRC]
NegDesignatorRange=1

**Comment by Metadorius** [comment]
Are designators an Ares or vanilla feature?

**Comment by GraionDilach** [comment]
Designators are coming from Ares. http://ares-developers.github.io/Ares-docs/new/superweapons/range.html#designators

Negative designators are inhibitors, that's how they are even called in the documentation so this proposal makes no sense. A better proposition would be (ofc in Ares) to unhardcode the stances for both logics into a separate tag.

**Comment by Metadorius** [comment]
Closing as this is not Phobos' territory.
