### ISSUE TITLE
Costom deathanim of vehicles&buildings when use some designated warheads

### ISSUE THREAD

**Issue by NetsuNegi** [Phobos-developers/Phobos#212]
Just like infdeathanims , when use warhead A to destroy units(include vehicle , aircraft and buildings), the custom deathanim will replace Explosion= in unit.

Flag:
[SomeWarhead]
DeathAnim=                ; animation

**Comment by YLanlan** [comment]
I think this function can be further enhanced. For example, whether to increase the "death anim" specified by this warhead, regardless of "not human = yes" or units with "death anims"

**Comment by NetsuNegi** [comment]
> 我认为这个功能可以进一步增强。例如，是否增加此弹头指定的“死亡动画”，而不管是“ not human = yes”还是具有“死亡动画”的单位

That's also great
