### ISSUE TITLE
Spyeffect: GIVE infiltrated player SW

### ISSUE THREAD

**Issue by DarkInsignia** [Phobos-developers/Phobos#22]
Currently, upon infiltration, the player who infiltrates can get a superweapon.
However, since superweapons are very flexible, it would be nice to be able to give the one that got infiltrated a super weapon as well.

Tag: SpyEffect.SuperWeapon.Owner=self | enemies

**Comment by Metadorius** [comment]
Remind me again, this is vanilla feature or Ares one?

**Comment by GraionDilach** [comment]
SpyEffect comes from Ares. http://ares-developers.github.io/Ares-docs/new/buildings/spyeffects.html

You can still hook into the spy logic, but that would lead to duplication and demanding Phobos users to not use SpyEffect.Custom. I'm not sure about the hook myself, but this code is ages-only, so looking at 0.8 would do.

**Comment by Metadorius** [comment]
I'd avoid such duplications, so again this request should be directed to AlexB.
