### ISSUE TITLE
[Vanilla Bug] building placement hotkey not responding.

### ISSUE THREAD

**Issue by Lylaktech** [Phobos-developers/Phobos#250]
### Description:
When using the hotkey for placing a building down (usually Q by default) and then canceling the placement then went back to pressing Q again, it stops responding and you have to place down the building regularly by clicking the cameo.

### Steps To Reproduce:
1. Queue a building
2. Once it is ready, select it with Q
3. Right click to unselect it
4. press Q again

### Expected Behaviour:
It should be selected just like the first time.

### Actual Behaviour:
The building does not get selected.

Additional Notes: Happens with armory tab buildings as well (W).

**Comment by AutoGavy** [comment]
+rep
