### ISSUE TITLE
Add C-like #define INI parser directive

### ISSUE THREAD

**Issue by MortonPL** [Phobos-developers/Phobos#26]
In INI files, allow to alias portions of text with shorter keywords, like with #define preprocessor directive in C language family. Possible merits: significant reduction of time spent copy-pasting (or, worse, typing by hand) INI fields as well as reduction of errors/typos caused by doing so. Additionally, this feature could be combined with [#include] section already existing in Ares, letting modders create pseudo-header files with their custom definitions. Hypothetical usage:

_At the start of rulesmd.ini:_
```
[#define:GenAllVehicleVoices]
VoiceSelect=GenAllVehicleSelect
VoiceMove=GenAllVehicleMove
VoiceAttack=GenAllVehicleAttackCommand
VoiceFeedback=
DieSound=GenVehicleDie
MoveSound=GrizzlyTankMoveStart
CrushSound=TankCrush
```

_Somewhere else:_
```
[MTNK]
...
Cost=700
Points=25
GenAllVehicleVoices
MovementZone=Normal
...
```

**Comment by Thrifinesma** [comment]
You can use this
```ini
[DEFINE_GenAllVehicleVoices]
VoiceSelect=GenAllVehicleSelect
VoiceMove=GenAllVehicleMove
VoiceAttack=GenAllVehicleAttackCommand
VoiceFeedback=
DieSound=GenVehicleDie
MoveSound=GrizzlyTankMoveStart
CrushSound=TankCrush

[MTNK]:[DEFINE_GenAllVehicleVoices]
...
...
```

**Comment by MortonPL** [comment]
I believe this issue is now redundant considering the plans to add [Phobos' own INI inheritance system](https://github.com/Phobos-developers/Phobos/issues/288).
