### ISSUE TITLE
[New Feature] An attach effect from Ares  that can effects units' weapon range 

### ISSUE THREAD

**Issue by Falaka21** [Phobos-developers/Phobos#273]
### Description:
Ares has AE options effect  that; Speed,RoF, Armor and Firepower and even Cloak for all TechnoTypes. I just want to add a S&D (Generals and ZH)  option about it.I don't know if  AEs  can effect WeaponRanges? Just an idea...
The other AE tags must support this for modders' decision.(Cumulative,Duration,   e.t.c.) 

### Possible Implementation:

```ini
[SomeWarhead]  
AttachEffect.WeaponRangeBonus="double" will be better, because" float" will be a bit more complex, I don't know about what "integer" does ? 

```

**Comment by Metadorius** [comment]
Ares feature requests should be sent to AlexB, not us. We can't do that.
