### ISSUE TITLE
[New Feature] Display digital health

### ISSUE THREAD

**Issue by tassder** [Phobos-developers/Phobos#282]
### Description:
Select units or buildings Display digital health
1. Full of health
Read the strength=XXX  in rules.ini
set up strength=XXX
Show below health bar strength /strength

2.Under attack
Show below health bar strength subtract hurt /strength

3.repair
Show below health bar (strength subtract hurt) add Maintenance volume /strength

### Possible Implementation:
UIMD.ini

[UISettings]
Displaydigitalhealth=（yes/no）

**Comment by secsome** [comment]
Follow the template and **rewrite** it more clearly is better.

**Comment by Falaka21** [comment]
I saw on youtube. I can't remember which ones, but  some mods have already use this. But I don't know how the modders manage to succed it. They use seperate shp.  pip. files  maybe, that shows  nearly real health, but not at exactly. Maybe ???

**Comment by Metadorius** [comment]
> I saw on youtube. I can't remember which ones, but some mods have already use this. But I don't know how the modders manage to succed it. They use seperate shp. pip. files maybe, that shows nearly real health, but not at exactly. Maybe ???

They are probably using HAres.

**Comment by secsome** [comment]
Can be extended in the implement of issue #376
