### ISSUE TITLE
Allow Multiple Linetrail

### ISSUE THREAD

**Issue by NetsuNegi** [Phobos-developers/Phobos#294]
In the original version, only one linetrail can be used for each projectile or unit, and it is forced to be generated in the center of the unit. I want to be able to use multiple linetrail and set offset for each linetrail.

### Possible Implementation:
```artmd.ini

[SOMESECTION]
UseLineTrail=yes            ; SJM
LineTrailColor=0,229,238
LineTrailColorDecrement=32  ; SJM
LineTrailOffset=-114,51,4
LineTrailColor2=0,229,238
LineTrailColorDecrement2=32  ; SJM
LineTrailOffset2=-114,-51,4
```

**Comment by AutoGavy** [comment]
https://github.com/Phobos-developers/Phobos/commit/566bb00fc813359a01b8ba73a10b39110ddfc4af
