### ISSUE TITLE
[Vanilla Bug] AltPalette=yes & unitxxx.pal shows above shroud

### ISSUE THREAD

**Issue by ayylmaoRotE** [Phobos-developers/Phobos#304]
### Description:

Animations using unit palette come up above shroud.

### Conditions:

Use AltPalette=yes on any animation and have it play under undiscovered terrain aka shroud
### Steps To Reproduce:

1. Slap AltPalette=yes on a recurring animation somewhere on the map
2. Hover over to said location and you will see the animation play through shroud

### Expected Behaviour:

Animation respects that the area is shrouded
### Actual Behaviour:

It has its own life and just appears above shroud

**Comment by NetsuNegi** [comment]
You can fix it by CustomPalette=unittem.pal in Ares.

**Comment by ayylmaoRotE** [comment]
> 
> 
> You can fix it by CustomPalette=unittem.pal in Ares.

This only solves the problem if you want to use unittem exclusively. Using AltPalette calls all unitxxx.pal meaning you can utilise different colours in each terrain type. Which is what this issue is asking for.

**Comment by Starkku** [comment]
> 
> 
> > You can fix it by CustomPalette=unittem.pal in Ares.
> 
> This only solves the problem if you want to use unittem exclusively. Using AltPalette calls all unitxxx.pal meaning you can utilise different colours in each terrain type. Which is what this issue is asking for.

`CustomPalette=unit~~~.pal` will make it use theater-specific variants.

**Comment by ayylmaoRotE** [comment]
^ Fixed, thanks!
