### ISSUE TITLE
[Phobos Bug]"Generate credits on impact" has no effect on missile (spawn) launcher

### ISSUE THREAD

**Issue by CkovMk** [Phobos-developers/Phobos#322]
e.g., try to set -150 credits to each V3ROCKET launch: 
Adding `TransactMoney=-150` to Warhead type of the spawner, [Special_2] (ik this would affect all spawners, just testing), does nothing.
Adding `TransactMoney=-150` to [V3WH] and [V3EWH], still no effect.

I'm using Phobos 2.2 and Ares 3.0, and I can confirm "Generate credits on impact" worked properly on other warhead types.
Is this a known issue, or I did something wrong?

thx!

**Comment by Metadorius** [comment]
@CkovMk Please re-test using latest nightly.

**Comment by Metadorius** [comment]
The fix has been attempted and the reporter didn't check further. If the bug persists in future it may be reopened.
