### ISSUE TITLE
[New Feature] a key to control support powers flashing the defense tab.

### ISSUE THREAD

**Issue by Lylaktech** [Phobos-developers/Phobos#333]
### Description:
Almost all mods now are adding support powers and the defense tab is always glowing because of it, I think a key to determine which of these support powers (basically the superweapons) is needed.

### Possible Implementation:
```ini
[SpaceLazerOfDoom]
important=yes
```

**Comment by Thrifinesma** [comment]
FlashSidebarTabFrames=0 will disable it
