### ISSUE TITLE
[New Feature] Add a new type of projectile——Straightline

### ISSUE THREAD

**Issue by Fantasycho** [Phobos-developers/Phobos#334]
Description:
Add a new projectile, which will let unit's bullet reach its target straightly

Final effect may look like the effect of projectile which set ROT=1,but never miss in all scenes.

Possible Implementation:

```ini

[TestWeapon]
Projectile=StraightLaserLine
…

[StraightLaserLine]
StraightLine=yes
…

```

Additional Files / Links:

The preview of new projectile‘s concept: 
https://www.bilibili.com/video/BV1VE41157Wk

(Just Straight Line's effect, ShrapnelWeapon is not included)

**Comment by Falaka21** [comment]
Yes, I am in favourite in this  also, I think this needs another infrastructure,since it could not be managed to gain until now.I watched the video in shock (positive way), even comet fragment (Shrapnel Weapon) goes in straight line !!! That was awesome!

**Comment by secsome** [comment]
Set `Gravity = 0` and `Gravity.HeightFix=yes` in the projectile by using the lastest dll.
