### ISSUE TITLE
[Phobos Bug] Extended building upgrades logic related player not lose

### ISSUE THREAD

**Issue by secsome** [Phobos-developers/Phobos#335]
### Description:

When you build some building upgrades to other players', you won't lose even if all your objects are all destoryed.

### Phobos Build:

Build20

### Conditions:

Player A build a PowerUp on Player B's building, and all Player A objects are destoryed later. 

### Steps To Reproduce:

1.Player A build a PowerUp building on Player B's
2.Destory all Player A's objects

### Expected Behaviour:

Player A lose

### Actual Behaviour:

Player A stay alive

### Additional Files / Links:

Reported by @Fantasycho

**Comment by Thrifinesma** [comment]
What if set `KeepAlive=no` (Ares tag) to the upgrades?

**Comment by Thrifinesma** [comment]
Resovled
