### ISSUE TITLE
[New Feature] Multiplayer Mode - Allowing multiple players to pick the same color

### ISSUE THREAD

**Issue by LukeZ-Mod** [Phobos-developers/Phobos#336]
Is it possible to add a new feature to allow >2 players to pick the same color in multiplayer mode?  If players select random, their color should still be distinct from the rest of the players. 

i.e  
player1    red
player2    red
player3    yellow
player4    yellow
etc. 

Currently, this option is available for AIs but not for human players

**Comment by Thrifinesma** [comment]
This block is set by XNA Client, I don't think the issue should be here
