### ISSUE TITLE
[New Feature] Infinite duration EMP effect

### ISSUE THREAD

**Issue by ajgunsauley** [Phobos-developers/Phobos#351]
### Description:
Allow EMP to have an infinite duration under the right circumstances.  Units that heal EMP would still be able to remove it.

### Possible Implementation:

```ini
[Warhead]
EMP.Duration=-1

OR

EMP.InfiniteDuration=true
```

**Comment by Falaka21** [comment]
Why? A very large number solves this. EMP.Duration=99999999999 stands for days. How many hours do you plan to play ?  :D

**Comment by AutoGavy** [comment]
https://www.youtube.com/watch?v=keYvZU3xTzQ

**Comment by ajgunsauley** [comment]
> Why? A very large number solves this. EMP.Duration=99999999999 stands for days. How many hours do you plan to play ? :D

Messy, but it works!
