### ISSUE TITLE
Sort out PowersUp interaction with Ares

### ISSUE THREAD

**Issue by Metadorius** [Phobos-developers/Phobos#36]
Apparently Ares grays out the PowerUp if there's no suitable building is present (need confirmation on this behavior). Of course, it wouldn't include the new `PowersUp.Buildings` tag, so that situation needs to be dealt with.
![image](https://user-images.githubusercontent.com/17500545/104089602-e7984000-5278-11eb-9f4b-c379bb67d42d.png)

**Comment by Belonit** [comment]
I performed the tests. And it seems the cameo is not blocked. At least in Ares 0.9 and Ares 3.0

**Comment by Metadorius** [comment]
Apparently that's a buildlimit implementation, in which case it's still an issue as only vanilla tag is accounted
