### ISSUE TITLE
[New Feature] Attack AircraftType units Script for FinalAlert2

### ISSUE THREAD

**Issue by BlackSnowMO** [Phobos-developers/Phobos#368]
### Description:

Request to add a new attack script for units in FinalAlert2 to focus AircraftType units. Since the only scripts that partially work are "Attack Anything" and "Patrol to Waypoint" in a way, I'd like to suggest adding a script dedicated to attack such type of units just like it's done for InfantryTypes and VehicleTypes.

![Aircraft](https://user-images.githubusercontent.com/90871871/133721558-64333015-6c12-458f-a295-2095f88bccaa.jpg)

```

### Additional Files / Links:
<!-- Attach additional files or links to content related to the feature report here (images/gifs/videos etc). -->

**Comment by secsome** [comment]
Should be included in #296 already.
