### ISSUE TITLE
LaserTrack

### ISSUE THREAD

**Issue by KusudaMikami** [Phobos-developers/Phobos#39]
The logic of the laser track is different from the laser. They are more like the laser cannon of a sci-fi battleship. The width and length of the laser track can be set (it does not hit directly like a laser, more like a linear projectile of a laser image), color
LaserTrack=yes/no LaserTrack.Width LaserTrack.Length LaserTrack.Colour It will be affected by the projectile option

LaserTrack=yes
LaserTrack.Width=1
LaserTrack.Length=1
LaserTrack.Colour=255,255,0
![1](https://user-images.githubusercontent.com/77217924/104793395-50ce0500-57dd-11eb-936b-649d7b3fdb68.png)
![2](https://user-images.githubusercontent.com/77217924/104793397-51ff3200-57dd-11eb-8bda-24ac7c55dd7a.png)

Picture effects can be achieved [it can imitate the trajectory of bullets], and the game lighting has little effect on it

**Comment by KusudaMikami** [comment]
LaserTrack=yes
LaserTrack.Width=1
LaserTrack.Length=1
LaserTrack.Colour=255,255,0
![2](https://user-images.githubusercontent.com/77217924/104793277-c84f6480-57dc-11eb-936e-cc54b2cb0a25.png)
![1](https://user-images.githubusercontent.com/77217924/104793278-c8e7fb00-57dc-11eb-98fc-4e8a57a0260f.png)
Picture effects can be achieved [it can imitate the trajectory of bullets], and the game lighting has little effect on it

**Comment by KusudaMikami** [comment]
> a
a
a

**Comment by MigEater** [comment]
You can already do practically the same with;
UseLineTrail= 
LineTrailColor=
LineTrailColorDecrement=

You could also make a vxl or shp projectile that looks like a short laser beam too.
