### ISSUE TITLE
[Phobos Bug] Random crashes

### ISSUE THREAD

**Issue by maistral** [Phobos-developers/Phobos#399]
### Phobos Build: 0.2.2

Crash dumps are here:
https://drive.google.com/file/d/1yKr4VQWUdes3X0tF197HWFJpXOOfYtas/view?usp=sharing
https://drive.google.com/file/d/1ZzLeViBiyG9KvCIrS9OhJaSLe26cyEiL/view?usp=sharing

**Comment by Belonit** [comment]
Since the dump links are no longer available, I will close this issue
