### ISSUE TITLE
Deploying a mind-controlled vehicle into a building doesn't grant access to superweapons even if it should

### ISSUE THREAD

**Issue by Starkku** [Phobos-developers/Phobos#4]
If you mind control an enemy unit that deploys into a building that grants access to superweapons, the superweapons won't become available when you deploy the unit. This appears to be only an issue when transfering the mind-control link from a vehicle to building, as access to superweapons is granted as expected if such building is mind-controlled directly. Likewise, before the fix that allows mind-control link to be transfered on deploy, access to superweapons was granted as expected as the building ownership was also permanently transfered.

**Comment by Metadorius** [comment]
Fixed in fde9ee0.

**Comment by Metadorius** [comment]
The fix doesn't fully work yet, reopening.

**Comment by Thrifinesma** [comment]
Already fixed
