### ISSUE TITLE
[Phobos Bug] Prism Forwarding Laser draw low quality laser

### ISSUE THREAD

**Issue by sKyHigh3110** [Phobos-developers/Phobos#410]
Prism Forwarding Laser draw low quality laser

Conditions: Hardcode & INI Code Changement

### Phobos version
Build 24 and higher

### Expected Behaviour:
- The Laser from the Prism Forwarding (both Default and Prism Forwarding by Ares). When a unit fire a laser (mostly Building, Prism Tower in this case) supposed to respect the laserthickness tag as well as the quality of the laser itself.

### Actual Behaviour:
- The Laser come from forwarded Prism draw a low quality laser and does not respect the laserthickness tag (both the supporting building and supported building). Can be observe in the detailed picture from the attachment.
- If no value is set on LaserThickness tag, it still draw a poor quality laser

### Additional Files / Links:
- no crashes or lagging causes by the issues just the quality of the laser.
![laser3](https://user-images.githubusercontent.com/92541032/137367764-0a2215ba-06ba-48ad-a5d2-6649d5232973.png)

![laser4](https://user-images.githubusercontent.com/92541032/137366109-e0c46072-3aca-4bb3-a32e-2892f1650613.png)

**Comment by sKyHigh3110** [comment]
Have this issue been noticed just yet?

**Comment by Metadorius** [comment]
I've seen the issue but yet to deal with it.
