### ISSUE TITLE
[Phobos Bug] Map Snapshot command crashing the game

### ISSUE THREAD

**Issue by mevitar** [Phobos-developers/Phobos#414]
As the title says, using the Ares Map Snapshot feature with Phobos causes the game to crash.

I tested several newest builds, including b22 and b24, and the crash happened in all of them, so it's clearly not anything recent.

To reproduce it, simply use the Map Snapshot feature on any map. It even crashes when used on the start of the game.

Ares itself does not crash when using Map Snapshot, even with same rules files.

Unfortunately, i am not able to provide the crashdump, but as it always happens, it should be easily accessible when needed.

**Comment by Starkku** [comment]
This is related to the waypoint range extension.

**Comment by Otamaa** [comment]
it is known , atleast for me , fixed it by simply move the buffer outside the loop of the `ScenarioClass_Write_Waypoints` hooks

**Comment by Belonit** [comment]
This bug should be fixed in the latest nightly builds. The problem was the incorrect definition of WriteInteger in YRpp
