### ISSUE TITLE
[Vanilla Bug] Retint map script disables RGB settings on light source

### ISSUE THREAD

**Issue by gangster-ppm** [Phobos-developers/Phobos#429]
### Description:

Retint map script keep light level setting on light source but disables all RGB settings

### Conditions:
Always

### Steps To Reproduce:
1.Apply Retint on any map.
2.Play it

### Additional Files / Links:
![image](https://user-images.githubusercontent.com/6735843/140893974-e9a8c85e-6270-4b87-b65f-de33b405d7d0.png)

**Comment by estherex** [comment]
Just a tip:
You can set Energy-support=0 in Structure options, and attach a tag to turn on this building after retint.

This method can avoid the bug.
