### ISSUE TITLE
[Phobos Bug] Crash on a mission load

### ISSUE THREAD

**Issue by CCRcmcpe** [Phobos-developers/Phobos#435]
### Description:

For testing purpose I intstalled Phobos on YR mod Mental Omega 3.3.6, when I start Epsilon mission 24 (a large and complex mission), game crashes on mission load.
### Phobos Build:

https://github.com/Phobos-developers/Phobos/releases/tag/build-24
### Steps To Reproduce:

1. Install Phobos on YR, with Mental Omega 3.3.6 installed.
2. Start Epsilon mission 24 with any difficulty.
3. Game crashes when loading mission.

### Additional Files / Links:

In `game folder/debug`, there's no any crash dumps except a `debug.log` (I see no obvious errors in it). If someone know how to let the game create a crash dump I will upload it though.
[debug.log](https://github.com/Phobos-developers/Phobos/files/7535320/debug.log)

**Comment by Falaka21** [comment]
Same happens to me also. Only the final mission of Epsilon! (The Babel) I thought, it was because of my insufficent hardware,but the other large missions work with no problem.So, by your announcement,I realized what caused the error.It is strange,somehow.Why only  on "Babel " mission ?

**Comment by secsome** [comment]
Had been fixed in the lastest develop.
The reason is one of the local variable's name is too long and corrupted the buffer
