### ISSUE TITLE
[New Feature] Custom Health Bar

### ISSUE THREAD

**Issue by Tatzq** [Phobos-developers/Phobos#451]
### Description:
There are great restrictions on HealthBar.
I hope someone is interested in this and can develop this logic to solve some problems

### Possible Implementation:
In UImd.ini or Independent ini
[HealthBar]
CustomHealthBar=yes
HealthBar.DisplayHealth=yes
HealthBar.DisplayHealthSHP=XXX.shp
HealthBar.DisplayHealthPal=xxxx.pal

**Comment by Metadorius** [comment]
Bro, can you please stop closing and reopening the issue?

**Comment by Metadorius** [comment]
Leave it as open and DON'T do anything else, thanks.
