### ISSUE TITLE
[Enhancement] Custom straight trail bullet speed

### ISSUE THREAD

**Issue by NetsuNegi** [Phobos-developers/Phobos#459]
### Description:
Now we can set Gravity=0 in some projectiles so this bullet will follow a straight trail, but we can't custom bullet speed until use other Gravity value.I think maybe sometimes we need faster or slower straight trail bullet.

### Possible Implementation:
In rulesmd.ini
[SomeWeapon]
Speed=double (In Yuri's Revenge, while arcing=true this flag is invalid. Maybe we can make it effective while its projectile has Gravity=0.)

**Comment by Falaka21** [comment]
Speed belongs to "Weapon" itself, not projectile...But, I am in favour of this also.Could be very useful.

**Comment by ayylmaoRotE** [comment]
A quick workaround (for short range weapons (range <6, tank cannons, etc) is to increase Gravity to let's say 30-50. It will not impact the arcing angle/trajectory and will still go straight, just much faster.

**Comment by NetsuNegi** [comment]
> 速度属于“武器”本身，而不是弹丸……但是，我也赞成这个。可能非常有用。

oh, I'm sorry I forget that.

**Comment by NetsuNegi** [comment]
> 一个快速的解决方法（对于短程武器（射程小于 6，坦克大炮等）是增加重力，比如说 30-50。它不会影响弧形角度/轨迹，并且仍然会直线前进，只是速度要快得多。

I had try it, but the bullet don't follow straight trail while Gravity=50, even it's faster.
