### ISSUE TITLE
[Phobos Bug] Cloak + Shield = object does not reveal itself if damaged

### ISSUE THREAD

**Issue by mevitar** [Phobos-developers/Phobos#462]
### Description:
RA2/YR usually reveals cloaked objects that receive damage, even if they don't get hit directly. All that has to happen is that the cell they are on is hit and the weapon deals damage, then they decloak for a brief moment and cloak back. This, however, does not happen for objects with shields.

### Expected Behaviour:
Since that's how it worked forever, one could expect that a shielded object will reveal itself each time it is being hit, just like unshielded objects do.

### Actual Behaviour:
Cloaked objects without a shield (or those that are damaged with a weapon that bypasses their shield) decloak for a brief moment each time a cell they are on is hit and they receive damage.
Cloaked objects with a shield do not decloak, even if they are damaged through force-firing the ground underneat them. As long as the shield is active, they will stay cloaked.

**Comment by Metadorius** [comment]
Do cloaked unshielded objects decloak if hit by a weapon with no damage? If yes it should be trivial to fix that, though I'd make it a separate feature, maybe someone would want the shields to allow objects to not uncloak on hit. ~~it's not a bug it's a feature ez~~

**Comment by mevitar** [comment]
No, they don't. It's tied to damage, so no damage = no decloak (this includes situations when relative damage is set to 0).

TBH, i don't really mind if it stays this way. I think many modders would like to disable this "damage reveals cloaked units" behavior for their mods anyway, since it makes cloaked units less of a threat. Giving cloaked units a shield is a workaround for that, but hopefully one day people would be able to customize whether an object decloaks when it's damaged or not.
