### ISSUE TITLE
[Phobos Bug] When you add a SecondaryWeapon to an Interceptor,  "bye bye"  to new logic ! 

### ISSUE THREAD

**Issue by Falaka21** [Phobos-developers/Phobos#473]
### Expected Behaviour:
Documentation says that Interception weapon  must  be a Primary weapon,AA and Inviso ! So,it must work independently from Secondaries !  If any interceptor must not include any SedondaryWeapons, The Documentation must declare it ! 

### Actual Behaviour:
 Even it is on a Primary, when you add a SecondaryWeapon to that unit,break happens,  PrimaryWeapon doesn't Intercept any enemy projectiles  anymore !

**Comment by Starkku** [comment]
This has presumably been fixed in 99b590cae99306863a598d53104c7b8fb1248c10. Try latest development nightly build and confirm.

**Comment by Metadorius** [comment]
Closing because the fix was made and there wasn't any response. @Falaka21 if you find out the fix is insufficient feel free to reopen.
