### ISSUE TITLE
[New Feature] Expand and Enhance Alpha Image

### ISSUE THREAD

**Issue by gangster-ppm** [Phobos-developers/Phobos#479]
### Description:
A list of ideas:
1. Use Alpha as Animation, or Animation as Alpha
2. Multi-framed Alpha
3. Disable RGB channel

### Possible Implementation:
[GAYARD_S1]
Image=GAYARD_S
Normalized=yes
Start=1
LoopStart=1
LoopEnd=6
LoopCount=1
Rate=200
Layer=ground

**;new tags**
IsAlpha.Image=yes ; Use Palette Index as Brightness level instead color, but respect: Layer, Rate, Start, LoopStart, LoopEnd, LoopCount
CLDisableBlue=true; like Combat Light on HW do
CLDisableGreen=true; This says the Combat Light should be red.

**Comment by secsome** [comment]
Alpha process has been taken over in Ares, I'm afraid that its almost impossible for Phobos to handle the AlphaImage processes.

**Comment by gangster-ppm** [comment]
Since AlexB had surfaced, may I request for the removal of this shamefully "Impossible" label?

**Comment by Thrifinesma** [comment]
> Since AlexB had surfaced, may I request for the removal of this shamefully "Impossible" label?

It is still `impossible` for Phobos, whoever had surfaced.
