### ISSUE TITLE
Sidebar tooltips with extended tooltips enabled do not always line-break properly

### ISSUE THREAD

**Issue by Starkku** [Phobos-developers/Phobos#49]
How sidebar tooltip strings are broken to multiple lines seems to change depending on if `ExtendedToolTips` is set to true or false under `[ToolTips]` in `uimd.ini`. Original behaviour (`ExtendedToolTips=false`) is fairly zealous with its line-breaking whereas the extended tooltips appear to have a much. much higher threshold for applying line breaks, which seems to cause problems with longer words and/or strings. This seems to apply to both `UIName` and `UIDescription` strings, although the difference in line-breaking behaviour can currently only be observed in case of the former for obvious reasons.

An example: left-hand side is with extended tooltips disabled, right-hand side is with extended tooltips enabled.
![tooltips](https://user-images.githubusercontent.com/1392346/105614447-3645ee00-5dd2-11eb-931f-45105b9ba38d.png)

**Comment by Metadorius** [comment]
Gluk tried to fix it but for now the fix just makes the tooltip be cut at the right so he disabled it for the time being.

**Comment by Belonit** [comment]
Fixed
