### ISSUE TITLE
Shields applied via WH have broken targeting (latest develop - 485 & 486)

### ISSUE THREAD

**Issue by ayylmaoRotE** [Phobos-developers/Phobos#490]
### Description:
Shields applied via WH have targeting issues. Below is a Prism Tank with a native shield, and another with the same shield applied via WH.

### Phobos Build:
[](https://github.com/Phobos-developers/Phobos/actions/runs/1650040879)

### Conditions:
Ares + Phobos. unreleased RotE 3.0 build, ini code below

### Steps To Reproduce:

1. Have a unit with a native shield (e.g. on TechnoType)
2. Clone the unit
3. Have the same shield type be applied via warhead

### Expected Behaviour:
Unit should be targetable without issue

### Actual Behaviour:
Healing weapons, ammo based weapons and dual weapon units can no longer attack the unit that received the shield via warhead

### Additional Files / Links:
Additional info from previous edit:

1. The cursor switches between attack and select very frequently (until respawn)
2. The shield cannot be targeted despite warhead versus being correct
3. Happens regardless of custom armor or vanilla armor on shield/versus
4. Blocks (ammo) Primary weapons that **can** and those that **cannot** target shields normally, it prevents the Secondary from being used so the unit stops attacking altogether. e.g. Sapper units
5. AttackFriendlies, CanTarget=owner or healing weapons, basically anything that targets friendlies, such as the weapon below or repair IFVs

https://user-images.githubusercontent.com/69301373/148046200-cb757cbf-57a7-4806-883b-9feeeaacdc0c.mp4

### Testing / Reproducing
For the sake of these tests I changed all my custom armors to vanilla "light"

**Shield information:**
[PHASESHD1]               ; ShieldType name
Strength=50                     ; integer
Armor=light                     ; ArmorType
Powered=false                  ; boolean
AbsorbOverDamage=true         ; boolean
SelfHealing=2%               ; double, percents or absolute
SelfHealing.Rate=0.12          ; double, ingame minutes
Respawn=0.25                    ; double, percents or absolute
Respawn.Rate=1.0               ; double, ingame minutes
BracketDelta=1                 ; integer - pixels
IdleAnim=PSHIELD                      ; animation
IdleAnim.OfflineAction=Hides   ; AttachedAnimFlag (None, Hides, Temporal, Paused or PausedTemporal)
IdleAnim.TemporalAction=Hides  ; AttachedAnimFlag (None, Hides, Temporal, Paused or PausedTemporal)
BreakAnim=MEDSHIELDEND                     ; animation
HitAnim=UCINIT                       ; animation

**Warhead used to apply shield:**
[SA]
Shield.AttachTypes=PHASESHD1          ; List of ShieldType names

**Target 1:**
[SREF]
Armor=light

**Target 2:**
[SREFUP]
ShieldType=PHASESHD1
Armor=light

### Scenario 1
>**Attacker 1 (AttackFriendlies):**
>[RefractorWH]
>Wall=no
>Verses=0%,0%,0%,10%,0%,0%,0%,0%,0%,0%,0%
>
>In this scenario, the Refractor can target SREFUP and SREF without issues, but once SREF gets the PHASESHD1 from [SA], it can no longer be targeted by the Refractor.

### Scenario 2
>**Attacker 2 (2 weapon aircraft / ammo unit):**
>[ORCA]
>Primary=Maverick
>Secondary=MaverickI
>Ammo=1
>
>[Maverick] (anti unit / building)
>Damage=70
>Warhead=ORCAAP
>
>[MaverickI] (anti infantry)
>Damage=70
>Warhead=ORCAAPI
>
>[ORCAAP]
>Verses=0%,0%,0%,145%,160%,200%,50%,60%,40%,0%,100%
>
>[ORCAAPI]
>Verses=100%,90%,80%,0%,0%,0%,0%,0%,0%,0%,0%
>
>The Harrier suffers exactly the same issues as the Refractor in Scenario 1 above. If we use the Harrier with 2 weapons (above), it cannot attack it at all, even if the primary weapon has anti vehicle versus. If the Harrier has 1 weapon, it will work without issues even on the shield applied by warhead.

### Scenario 3
>**Attacker 3 (repair weapon)**
>[RepairBullet]
>Damage=-50
>Warhead=Mechanical
>
>[Mechanical]
>Verses=0%,0%,0%,70%,75%,80%,0%,0%,0%,0%,100%
>
>SREF and SREFUP can be repaired by this weapon, the shield on SREFUP included. But if the shield is applied to SREF via warhead, the same issue occurs where it cannot target the unit anymore.

**Comment by Metadorius** [comment]
Resolved in the latest develop.
