### ISSUE TITLE
[Phobos Bug] develop-4933ed3 crashes

### ISSUE THREAD

**Issue by mevitar** [Phobos-developers/Phobos#495]
Game crashed during a game. The EIP 007CFC9F also seems familiar. A previous crash i reported had EIP 007CFD30, which might be in the same function.
https://drive.google.com/file/d/19ShtD5MlvIHrRhyFanOnxPAXMlIEZ6-c/view

This crash was strange. The screen suddenly turned black for few seconds and then Windows reported that YR has crashed. There was no way to get a crashdump, so i put here whatever i could get.
https://drive.google.com/file/d/1INmzZG3ue-ffrovsGz4jiGarr51Ti9_8/view

**Comment by Starkku** [comment]
The crash that has salvageable information is associated with a known issue regarding shield animations and particularly interaction with cloaking objects that should have been resolved in develop branch now. Will close this one, but if the crashes persist on latest develop branch nightly build or future devbuilds, open a new issue.
