### ISSUE TITLE
[Phobos Bug] develop-4d776bf random crash

### ISSUE THREAD

**Issue by mevitar** [Phobos-developers/Phobos#497]
Random crash, possibly related to cloak+shield buildings since they were being damaged shortly before the crash. The reason might be something completely unrelated, though, as i damaged (and killed them) multiple times before without any crashes.
https://drive.google.com/file/d/1tV2p89_tKiB3fdy5V1V1CPJX_rRBkVZy/view

**Comment by Starkku** [comment]
This crash is associated with a known issue regarding shield animations and particularly interaction with cloaking objects that should have been resolved in develop branch now. Will close this one, but if the crashes persist on latest develop branch nightly build or future devbuilds, open a new issue.
