### ISSUE TITLE
Font file is not compatible with Chinese

### ISSUE THREAD

**Issue by GrosserKurfurst** [Phobos-developers/Phobos#50]
Font file with new characters added
Many Chinese characters are not supported
This is a language that contains a lot of Chinese game.fnt
Hope to add new characters
[FNT.zip](https://github.com/Phobos-developers/Phobos/files/5864408/FNT.zip)

**Comment by GrosserKurfurst** [comment]
If you can, please add this symbol 「」

**Comment by Metadorius** [comment]
Is this font custom drawn or...? Also who do we credit for the characters found there?

**Comment by Metadorius** [comment]
@GrosserKurfurst why was the issue closed?
