### ISSUE TITLE
[Phobos Bug] bunch of develop-df778ed crashes

### ISSUE THREAD

**Issue by mevitar** [Phobos-developers/Phobos#502]
Happened at random point during the game, likely caused by the same issue but not sure what.
https://drive.google.com/file/d/1WyrJy11HzZDjwj4arqB3MaY6L7v77Mr1/view
https://drive.google.com/file/d/1WeRHoaZX3zqtM4bRF-UNesoXLzsLHkr9/view
https://drive.google.com/file/d/13-nSryf-3k43qSO2uOhIRaD4wdQOS2a7/view
https://drive.google.com/file/d/1zIgL1yo8icGLtJoVyhK89GRbt18x_c8q/view
https://drive.google.com/file/d/1RRd3ilN6VJ3ULHZdZtlX6AGPpE4X6dJy/view

**Comment by Starkku** [comment]
All of these crashes are associated with a known issue regarding shield animations and particularly interaction with cloaking objects that should have been resolved in develop branch now. Will close this one, but if the crashes persist on latest develop branch nightly build or future devbuilds, open a new issue.
