### ISSUE TITLE
[New Feature] Designator/Inhibitor House and Range can be define in a SuperWeaponType

### ISSUE THREAD

**Issue by BIGBADAUD999** [Phobos-developers/Phobos#514]
### Description:
Just like title says, make the Designator/Inhibitor's House and Range changable in the Super Weapon.

### Possible Implementation:
; rulesmd.ini
[SomeSuperWeapon]
SW.DesignatorsRange=114 ; (integer - cells) - Range in cells around the unit or structure in SW.Designators that becomes targetable by super weapons requiring this object as designator. Defaults to [TechnoType]►Sight.
SW.InhibitorsRange=514 ; (integer - cells) - Range in cells around the unit or structure in SW.Inhibitors that becomes untargetable by super weapons having this object set as inhibitor. Defaults to [TechnoType]►Sight.
SW.DesignatorsHouse=ally ; (list of HouseTypes) - list of Designator's House Enumeration (none|owner/self|allies/ally|team|enemies/enemy|all)
SW.InhibitorsHouse=enemy ; (list of HouseTypes) - list of Designator's House Enumeration (none|owner/self|allies/ally|team|enemies/enemy|all)

**Comment by Metadorius** [comment]
We are not dealing with Ares features because it is impossible for us to do that. Go ask AlexB for that.
