### ISSUE TITLE
[Phobos Bug] Light is rendered strangely in superweapons using Type=MultiMissile 

### ISSUE THREAD

**Issue by Elivicti** [Phobos-developers/Phobos#558]
### Description:
With following light settings, it's too bright at high places but too dark at low places.
```ini
Light.Blue=50
Light.Red=50
Light.Green=50
Light.Ambient=75
```
<img width="860" alt="Snipaste_2022-03-16_12-50-34" src="https://user-images.githubusercontent.com/50987873/158726658-4ab0b3bd-a2c2-4ecc-822c-47069f767fe8.png">

However, this is not the situation when using Type=LightningStorm (with same light settings)
<img width="859" alt="Snipaste_2022-03-16_12-52-44" src="https://user-images.githubusercontent.com/50987873/158727023-763813cc-25f0-44a7-8819-c0da373d6e20.png">

### Expected Behaviour:
Type=MultiMissile should render light in the same way that Type=LightningStorm does.

**Comment by secsome** [comment]
This is an Ares issue instead of Phobos one
