### ISSUE TITLE
[Phobos bugs]

### ISSUE THREAD

**Issue by zhnjsacdjkn** [Phobos-developers/Phobos#566]
Dear Phobos Developers,now you build the newest Phobos 27,here are some bugs you can solve and some functions which you write them in Phobos can be more interesting.BUGS:When I am in skirmish 'Watch The War' Game Mode(I am using XNA CNCnet Client),and I release the superweapon:Nuke Attack[NukeSpecial] to aim a tree,then the Nuke Mssile down and it will IE immediately.On the other hand,when load in skirmish 'Watch The War'Game Mode,it somtimes IE,too.So the two bugs I really hope you can fix them as possible as fastly,thank you very much!

**Comment by Metadorius** [comment]
Please, spend some effort to actually follow the template so we can understand the problem clearly.
