### ISSUE TITLE
[Phobos Bug] Negative ShieldType SelfHealing not working if shield has full strength

### ISSUE THREAD

**Issue by abyo666** [Phobos-developers/Phobos#571]
### Description:

If shield has full strength, shield's negative SelfHealing doesn't work. The shield should deduct its strength at the time.
_If this behavior is not actually a bug, I think it's confusing enough to be mentioned in doc._

### Phobos Build:

[https://github.com/Phobos-developers/Phobos/releases/tag/build-27](url)

### Conditions:

Ares3.0 + Phobos build27 (it appears in earlier builds too)

`[ShieldTypes]`
`0=SOMESHIELDTYPE`

`[SOMESHIELDTYPE]`
`Strength=50`
`InitialStrength=50`
`Armor=none`
`Powered=false`
`AbsorbOverDamage=false`
`SelfHealing=-10`
`SelfHealing.Rate=0.1`

`[E1]`
`ShieldType=SOMESHIELDTYPE`

There isn't any other INI changes.

### Steps To Reproduce:

1.Enter the game and see GIs

### Expected Behaviour:

GI's shield should reduce its strength at the time.

### Actual Behaviour:

GI's shield doesn't reduce its strength unless GI was hit.

**Comment by Starkku** [comment]
Has a fix pending in PR #535.
