### ISSUE TITLE
[New Feature] Duration Extended

### ISSUE THREAD

**Issue by DeathFishAtEase** [Phobos-developers/Phobos#579]
### Description:
In NPEXT, when calculating the EMP duration, the game will consider the warhead versus, but there is no such effect in Ares. If you want to make a similar effect, you can only use cumbersome methods such as sub weapons. 
It is hoped that the action time of EMP, IronCurtain and AttachEffect.etc in Phobos will same to the normal warhead effect which will consider Versus and PercentAtMax .etc 
**Mainly EMP**

### Possible Implementation:

[WarheadType]
[EMP|IC|AE|.etc].ObeyVersus=(boolean);(def=no)

**Comment by Starkku** [comment]
EMP, IronCurtain warhead and AttachEffect are Ares-implemented logics not available to Phobos.
