### ISSUE TITLE
[New Feature] DominatorEffectAerialobject and Bridge repair hut

### ISSUE THREAD

**Issue by DeathFishAtEase** [Phobos-developers/Phobos#581]
### Description:
In the original game, if some units that can take off successfully take off ,like SHAD. they will not be affected by the PsychicDominator when SuperWeapon launch, the PsychicDominator has no effect on Airunits, Similarly, it has no effect on Occupier or Objects in transport vehicles

In addition, Ares has added a new label: Dominator.CaptureImmuneToPsionics。 However, when using this tag, it often takes effect on the bridge repair hut near the target, resulting in some problems. I hope to add an identification of neutral targets

### Possible Implementation:

in rulesmd.ini
[SuperWeaponType]
Type=PsychicDominator
Dominator.AffectsAircraft=(boolean);(def=no)
Dominator.AffectsOccupy=(boolean);(def=no)
Dominator.AffectsPayload=(boolean);(def=no)
Dominator.AffectsNeutral=(boolean);(def=no)

**Comment by Starkku** [comment]
Dominator superweapon has effectively been reimplemented on Ares side and thus cannot be altered in Phobos.

**Comment by DeathFishAtEase** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
