### ISSUE TITLE
[Phobos Bug] Shield wouldn't automatically lose strength unless hit.

### ISSUE THREAD

**Issue by 8abs** [Phobos-developers/Phobos#602]
I set the health recovery of a shield to a negative number（SelfHealing=-10%）, but in the game, the shield will not automatically lose strength as I set so until I attack the shielded unit with other units. It turned out that if a shield's SelfHealing is a negative number, it can't
function unless it receives damage.
I have tested this a lot of times, so I'm sure this problem is a bug but not my own mistake or what.

**Comment by Starkku** [comment]
Which Phobos version are you using?

**Comment by 8abs** [comment]
build 27. Is that problem already fixed in the later version? OMG It's awkward

**Comment by Metadorius** [comment]
Should be fixed in develop.
