### ISSUE TITLE
[Phobos Bug] HarvesterCounter believes that the harvester in Chrono ready state is not working

### ISSUE THREAD

**Issue by DeathFishAtEase** [Phobos-developers/Phobos#603]
### Description:
If a CMIN on its way back is walking because GAREFN is occupied, the HarvesterCounter believes that the CMIN is not working

### Phobos Build:
[Build 27](https://github.com/Phobos-developers/Phobos/releases/tag/build-27)

### Steps To Reproduce:
Make the number of CMIN more than XAREFN

### Expected Behaviour:
CMIN is still on its way back to the mine and has not changed to a non mission state, which should not be considered as not working. And the resulting high-frequency flashing of the HarvesterCounter is very annoying and meaningless (because the harvester is actually still working and does not need players to give it new instructions)

### Actual Behaviour:
The CMIN in this state is regarded as not working, and make the HarvesterCounter flashes at a high frequency

### Additional Files / Links:
![HarvesterCounter_CMIN_Bug](https://user-images.githubusercontent.com/89088785/163991040-34854543-9999-4366-a3dd-1bb48a477efd.gif)

**Comment by chaserli** [comment]
You may check my solution for this. This is supposed to be a helper utility, the criteria may differ between people.

我觉得移动的guard状态的矿车应该算是在采矿状态中的，保险起见我加了没被选择的情况，可能会有误判，但闪烁的情况会大大减少

**Comment by DeathFishAtEase** [comment]
> You may check my solution for this. This is supposed to be a helper utility, the criteria may differ between people.
> 
> 我觉得移动的guard状态的矿车应该算是在采矿状态中的，保险起见我加了没被选择的情况，可能会有误判，但闪烁的情况会大大减少

我试了试，确实变得少多了，除了偶尔会在矿场倒矿的时候因为实在太挤而真的罢工:P

**Comment by DeathFishAtEase** [comment]
>...
I remember you changed MCV's wayfinding before. Do you want to try to change the wayfinding of the harvester? They are too stupid
你之前改过MCV的寻路，要不要尝试一下修改矿车的寻路，这(↓)实在是太要命了
![hard work](https://user-images.githubusercontent.com/89088785/167251091-c45814a1-6dcd-4a0f-9dd8-c3a1d9a29331.png)
![hardwork](https://user-images.githubusercontent.com/89088785/167251094-fd5d3006-c816-4851-9be7-bd238bf5d535.png)
![hardwork2](https://user-images.githubusercontent.com/89088785/167251095-c38d804d-e56b-407c-927a-5aa82c429ef7.png)
![000](https://user-images.githubusercontent.com/89088785/167251099-ade77990-1eda-46c7-9a9a-ebbb1d10b9c1.jpg)

**Comment by chaserli** [comment]
> > ...
> > I remember you changed MCV's wayfinding before. Do you want to try to change the wayfinding of the harvester? They are too stupid
> > 你之前改过MCV的寻路，要不要尝试一下修改矿车的寻路，这(↓)实在是太要命了
> > ![hard work](https://user-images.githubusercontent.com/89088785/167251091-c45814a1-6dcd-4a0f-9dd8-c3a1d9a29331.png)
> > ![hardwork](https://user-images.githubusercontent.com/89088785/167251094-fd5d3006-c816-4851-9be7-bd238bf5d535.png)
> > ![hardwork2](https://user-images.githubusercontent.com/89088785/167251095-c38d804d-e56b-407c-927a-5aa82c429ef7.png)
> > ![000](https://user-images.githubusercontent.com/89088785/167251099-ade77990-1eda-46c7-9a9a-ebbb1d10b9c1.jpg)

I didn't try to change MCV's pathfinding in the other PR, I just reset its destination, it still does the pathfinding itself. Change the default A* attempt is definitely out of my capabilities for the moment

**Comment by DeathFishAtEase** [comment]
> > > ...
> > > I remember you changed MCV's wayfinding before. Do you want to try to change the wayfinding of the harvester? They are too stupid
> > > 你之前改过MCV的寻路，要不要尝试一下修改矿车的寻路，这(↓)实在是太要命了
> > > ![hard work](https://user-images.githubusercontent.com/89088785/167251091-c45814a1-6dcd-4a0f-9dd8-c3a1d9a29331.png)
> > > ![hardwork](https://user-images.githubusercontent.com/89088785/167251094-fd5d3006-c816-4851-9be7-bd238bf5d535.png)
> > > ![hardwork2](https://user-images.githubusercontent.com/89088785/167251095-c38d804d-e56b-407c-927a-5aa82c429ef7.png)
> > > ![000](https://user-images.githubusercontent.com/89088785/167251099-ade77990-1eda-46c7-9a9a-ebbb1d10b9c1.jpg)
> 
> I didn't try to change MCV's pathfinding in the other PR, I just reset its destination, it still does the pathfinding itself. Change the default A* attempt is definitely out of my capabilities for the moment

xb,  at least this problem is much better than before
