### ISSUE TITLE
AI Script of Building Target Using Building's ID Instead of The Index of the Building

### ISSUE THREAD

**Issue by Daiki9527** [Phobos-developers/Phobos#611]
### First check

- [X] The suggestion is **NOT** related to functionality of Ares, HAres, Kratos or any other YR engine extension.
- [x] The suggested feature / enhancement is **NOT** implemented in Ares/Phobos yet and the existing possibilites are not viable or good enough to achieve the wanted result.
- [X] I agree to elaborate the details if requested and provide thorough testing if the feature is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I thought out how the feature / enhancement should work and described it in the most detailed and clear way.

### Description

We know that in aimd.ini, in a ScriptType, like:

[0CE3323C-G]
Name=Allied C-Legion vs Ally Con
0=54,0
1=53,0
2=47,2

The third action is to get close to the BuildingTypes Index 2=GACNST, Least threat
But what if we use a larger Index and this index is easily changed as i want to sort it out in a section where there are indexes of same faction. Pointless i know
Using the Building's ID would be much more convenient.

Like:
[0CE3323C-G]
2=47,GACHST,0

Now the action is to get close to the building GACNST with least threat,clear enough

### INI code

```ini
;Origin
[ScriptTypes]
Index=Action,'Argument(Plus Computed Value)'

'Action could be:
46=Attack Enemy Structure
47=Move To Enemy Structure
56=Chronosphere TaskForce
57=Chronowarps TaskForce
58=Move To Friendly Structure'

Argument could be any index of BuildingTypes //Which is complicated if we do not use an Ai Editor

'Computed Value                                     | Description
0 (Hex 0x0) + Building Index                   | Select the instance of the building with least threat
65536 (Hex 0x10000) + Building Index   | Select the instance of the building with highest threat
131072 (Hex 0x20000) + Building Index | Select the instance of the building which is nearest
196608 (Hex 0x30000) + Building Index | Select the instance of the building which is farthest'

;New Set could be:
;In Aimd.ini
[ScriptTypes]
Index='Action',BuildingID,'Description

Description:
0:Select the instance of the building with least threat
1:Select the instance of the building with highest threat
2:Select the instance of the building which is nearest
3:Select the instance of the building which is farthest'

;In Rulesmd.ini
[General]
ScriptsUseBuildingIndex=no;to make the function available
```

**Comment by FS-21** [comment]
I'm lost.

You clicked "The suggested feature / enhancement is NOT implemented in Ares/Phobos yet and the existing possibilites are not viable or good enough to achieve the wanted result."

Did you read the documentation of new Script Actions? Specially these:
https://phobos.readthedocs.io/en/latest/New-or-Enhanced-Logics.html#moving-team-to-techno-location

**Comment by FS-21** [comment]
Ok, what you suggested is to be able to use IDs instead of numbers in ScriptType Actions like in YR MAP Actions. That isn't possible with the ScriptType structure.

In the link I posted and that will come in Phobos 0.3 allows you to have "infinite" lists of >= 1 units if you want in the new rulesmd.ini section called [AITargetType]
