### ISSUE TITLE
Shrapnel enhancement bug

### ISSUE THREAD

**Issue by kmlmhd** [Phobos-developers/Phobos#616]
### First check

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

### Description

Shrapnel has been triggered when the unit attacks the enemy's large building, but it can not disperse.

### Phobos Version

Phobos development build 27

### Steps to reproduce

1.
2.
3.
...

### Expected behaviour

https://user-images.githubusercontent.com/104789001/166391756-bbd3ce80-5a5c-4bf3-ad89-25f46cae007b.mp4

### Actual behaviour

https://user-images.githubusercontent.com/104789001/166391693-cdd5fecd-08a8-4f30-aadf-16b2ed35271f.mp4

**Comment by mevitar** [comment]
Shrapnels have a limited range (which i think is hardcoded), so the game might be unable to find cells unoccupied by the ConYard within that range.

**Comment by NetsuNegi** [comment]
I used debug mode and found that maybe it just hit this building again.

**Comment by kmlmhd** [comment]
> I used debug mode and found that maybe it just hit this building again.

那是否有办法修复呢?

**Comment by NetsuNegi** [comment]
> > I used debug mode and found that maybe it just hit this building again.
> 
> 那是否有办法修复呢?

I don't know.

**Comment by NetsuNegi** [comment]
> > I used debug mode and found that maybe it just hit this building again.
> 
> 那是否有办法修复呢?

我不清楚该如何修复，因为我并非这个功能的作者

**Comment by kmlmhd** [comment]
> 我不清楚该如何修复，因为我并非这个功能的作者

哦，我明白了！多谢回复！！！
