### ISSUE TITLE
Reverse/Neg Designators

### ISSUE THREAD

**Issue by 8abs** [Phobos-developers/Phobos#617]
### First check

- [x] The suggested feature / enhancement is **NOT** implemented in Ares/Phobos yet and the existing possibilites are not viable or good enough to achieve the wanted result.
- [X] I agree to elaborate the details if requested and provide thorough testing if the feature is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I thought out how the feature / enhancement should work and described it in the most detailed and clear way.

### Description

ARES has a designator feature for superweapons to be allowed to put in the designator range. I think Phobos should add a reverse designator (or negative designator) for owner's superweapons not to be allowed to put inside some user's own or allies' units' neg-designator range.

### INI code

```ini
[SomeTechnoType]
NegDesignatorRange=0 <int,double>

[SomeSuperWeaponType]
SW.NegDesignators=none <some technotypes, maybe including shieldtypes>
```

**Comment by Metadorius** [comment]
![image](https://user-images.githubusercontent.com/17500545/166410336-c23524d1-af16-4dc4-9053-a491daa5d3ac.png)
The suggestion checks are not something you can discard at will. We DO NOT implement Ares improvements, please suggest that to AlexB.
