### ISSUE TITLE
AI using countries-specific defenses list

### ISSUE THREAD

**Issue by Danielovich7** [Phobos-developers/Phobos#64]
As of now, the AI does not respect the "RequiredHouses=" or "ForbiddenHouses=" tags on defenses buildings that are listed under "AlliedBaseDefenses=", "SovietBaseDefenses=" or "ThirdBaseDefenses=". Fixing this issue would make it possible for the AI to respect country-specific requirements for defenses building.

It could work this way : under any country entry in the [Countries] list, a tag (maybe "AI.CountryDefenses=") could be used to list which building types are considered are defenses by the AI. It could work exactly like Ares's "AI.BaseDefenses=" (which only works for Sides and not Countries).

**Comment by evanb90** [comment]
You can actually accomplish this right now, without need for a new feature.

All you need to do is remove the country from the Owner= list for that building.
For example
```
[GAPILL]
Owner=British,Germans,Alliance,Russians,Confederation,Africans,Arabs,YuriCountry
```
Would prevent American/French AI from building the Pillbox.
