### ISSUE TITLE
Allow PlacementPreview.Shape to support shps for different theaters

### ISSUE THREAD

**Issue by Cpj636** [Phobos-developers/Phobos#642]
### First check

- [X] The suggestion is **NOT** related to functionality of Ares, HAres, Kratos or any other YR engine extension.
- [X] The suggested feature / enhancement is **NOT** implemented in Ares/Phobos yet and the existing possibilites are not viable or good enough to achieve the wanted result.
- [X] I agree to elaborate the details if requested and provide thorough testing if the feature is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I thought out how the feature / enhancement should work and described it in the most detailed and clear way.

### Description

For different theaters, PlacementPreview will use different shp files by default like NAREFENMK's last frame for snow theater and NGREFENMK's last frame if other NXREFENMK missing. However, when it comes to customizations through PlacementPreview.Shape,  it cannot switch files according to prefix G/A/D etc. 
Hope there could be a way for PlacementPreview.Shape to load different shp files on different theaters. For example, allow PlacementPreview.Shape to load different files according to the second filename character. Or allow PlacementPreview.Shape to load different files according to the last filename character like seal.shp, seala.shp and seald.shp.

### INI code

```ini
No additional ini codes needed.
```

**Comment by Belonit** [comment]
@Cpj636 Please check this PR #710
