### ISSUE TITLE
"PreImpactAnim" went wrong when "Trajectory=Straight" enabled

### ISSUE THREAD

**Issue by Morrlean** [Phobos-developers/Phobos#644]
### First check

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

### Description

I created an unit that acted like Future Tank in Red Alert 3. As stated in the first video,it used laser beam to attack and warhead exploded after the "PreImpactAnim" finished when Phobos build 28 was unreleased. 

But I meet a new problem now. I created a new projectile with “Trajetory=Straight” enabled. The warhead explodes at the same time as "PreImpactAnim" plays (please watch the second video). It happens on motionless targets. The weapon also acts weird when the projectile hit the building because the "PreImpactAnim" played outside the buliding but the warhead's animation played in the center after that. 
In addition, "PreImpactAnim" behaves normal if the projectile is just a cannonball with  "Arcing=yes"(watch video3).

### Phobos Version

Build 28

### Conditions to reproduce

Ares 3.0, Phobos Build 28, YR1.001

### INI code

```ini
[NeutronCannon]
Damage=140
ROF=125
Range=7
Projectile=FutureBall
Trajectory.Speed=50
Warhead=FutureWH
Report=FutureTankFire
Anim=FutureTankMuzzle
Bright=yes
Burst=2
Burst.Delays=2

[FutureBall]
Image=FTBALL
SubjectToCliffs=yes
SubjectToElevation=yes
SubjectToWalls=no
Trajectory=Straight
Shadow=no
Ranged=yes

[FutureWH]
CellSpread=4
PercentAtMax=0.1
CellSpread.MaxAffect=1
Wall=yes
Wood=yes
Verses=100%,100%,100%,100%,100%,100%,100%,100%,100%,100%,100%
InfDeath=2
AnimList=FTEXP
Bright=yes
PreImpactAnim=FTPREIMPT
AffectsAllies=no
```

### Steps to reproduce

1. Projectile: Trajetory=Straight
2. Warhead: PreImpactAnim is used.

### Expected behaviour

The warhead's animation plays after PreImpactAnim ended.

### Actual behaviour

PreImpactAnimnimation played at the same time as  warhead's animation did. The damage took effect too soon.

### Additional context

https://user-images.githubusercontent.com/101973321/169602770-a563dfe1-3114-4f9b-ba91-89df6540d263.mp4

https://user-images.githubusercontent.com/101973321/169602785-95366014-1b9b-4271-b054-3fe7fd38ef39.mp4

https://user-images.githubusercontent.com/101973321/169602789-d890e62f-ab6e-4522-873b-aeed1e7146ab.mp4

**Comment by Metadorius** [comment]
@Morrlean try latest development branch nightly, the bug should be fixed. Reopen if it's not.
