### ISSUE TITLE
AI crash when DeployFireWeapon=-1 is used

### ISSUE THREAD

**Issue by ayylmaoRotE** [Phobos-developers/Phobos#646]
### First check

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

### Description

AI does not handle `DeployFireWeapon=-1` and crashes the game the moment it is utilised.

Dump uploaded to phobos chat channel, crash snip below:
Exception code: C0000005 at 006F77F

[except.txt](https://github.com/Phobos-developers/Phobos/files/8749349/except.txt)
9

### Phobos Version

B27 and B28

### Conditions to reproduce

Give [GGI] an AA only `MissileLauncher` weapon clone and add `DeployFireWeapon=-1` to [GGI]

### INI code

```ini
[GGI]
Primary=MissileLauncher (Projectile = AG=yes, AA=no)
ElitePrimary=MissileLauncherE
Secondary=AAMissileLauncher (Projectile = AG=no, AA=yes)
EliteSecondary=AAMissileLauncherE
DeployFireWeapon=-1
```

### Steps to reproduce

1. Add DeployFireWeapon=-1 to GGI
2. Add an Allied AI to the game
3. Start game and wait until AI uses GGI
...

### Expected behaviour

Unit should switch weapons based on target

### Actual behaviour

Game crashes because AI cannot handle the tag

**Comment by Starkku** [comment]
Should be fixed in latest develop nightly build. Please test and report back.

**Comment by ayylmaoRotE** [comment]
Yes confirming it has fixed AI crashes
