### ISSUE TITLE
Allow sorting sidebar icons

### ISSUE THREAD

**Issue by FS-21** [Phobos-developers/Phobos#66]
After reading how works in YR the cameo order:
https://www.modenc.renegadeprojects.com/Cameo_Sorting

I suggest a tag in artmd.ini or in rulesmd.ini to be able to override the current checks the game does, something like:
[UNIT/STRUCTURE ID]
...
CameoPriority=**Integer**
...

Where the lowest value means to be placed in the top of the sidebar.

Default value can be -1 or 0 for using the original RA2/YR method on that cameo, prioritizing the ordered cameos over the others.

In the case of using the same integer for different units/structures this can use the "first come first serve" for sorting or apply the default YR behaviour on these conflictive icons.

Because Super Weapons doesn't have Artmd.ini entries I thought not applying this idea to those SW icons, just structures/units.

**Comment by OmegaBolt** [comment]
IMO this would be _most_ useful for superweapons given I think it's just alphabetical or something (I think reverse alphabetical?). Guaranteeing superweapons are in the same order each time would make them a lot easier to find. Technos are already predictable.

**Comment by Thrifinesma** [comment]
#192
