### ISSUE TITLE
Your new feature title here

### ISSUE THREAD

**Issue by NotAGeek25** [Phobos-developers/Phobos#660]
### First check

- [X] The suggestion is **NOT** related to functionality of Ares, HAres, Kratos or any other YR engine extension.
- [X] The suggested feature / enhancement is **NOT** implemented in Ares/Phobos yet and the existing possibilites are not viable or good enough to achieve the wanted result.
- [X] I agree to elaborate the details if requested and provide thorough testing if the feature is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I thought out how the feature / enhancement should work and described it in the most detailed and clear way.

### Description

"AttackFriendlies=yes" can only let a unit also attack its friendlies, but can't prevent it from still attacking enemies. Even if "AffectsEnemies=no" is added to this unit's warhead, it still don't stop itself from attack enemies' units (of course, without any actual damage & effect).

There should be 2 lines of ini to determine if a technotype could only aim its owner's or allies' technotypes.

### INI code

```ini
[SomeTechnoType]
OnlySeekFriendlies=no
OnlySeekOwner=yes
```

**Comment by Falaka21** [comment]
Stable Phobos already has ........


"Weapon targeting filter[](https://phobos.readthedocs.io/en/latest/New-or-Enhanced-Logics.html#weapon-targeting-filter)
You can now specify which targets or houses a weapon can fire at. This also affects weapon selection, other than certain special cases where the selection is fixed.

Note that CanTarget explicitly requires either all or empty to be listed for the weapon to be able to fire at cells containing no TechnoTypes.

In rulesmd.ini:

[SOMEWEAPON]         ; WeaponType
CanTarget=all        ; list of Affected Target Enumeration (none|land|water|empty|infantry|units|buildings|all)
CanTargetHouses=all  ; list of Affected House Enumeration (none|owner/self|allies/ally|team|enemies/enemy|all)"...........

I know, this belongs to "Weapons", and you are talking about "Unit" itself... But it goes the same destination ,by different route...
