### ISSUE TITLE
Script 95-98, 106-109 would result in Reconnection error

### ISSUE THREAD

**Issue by handama** [Phobos-developers/Phobos#661]
### First check

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

### Description

When a team is executing Script 95-98, 106-109, it is very likely to RE.

### Phobos Version

b28

### Conditions to reproduce

vanilla YR 1.001 + ARES3.0p1 + Phobos Build28
(if change b28 back to b27, everything goes well)

### INI code

```ini
in a map:
[01000001]
0=95,1 ;I also tested 99
1=0,0
Name=E1S

[01000002]
0=10,E1
Name=E1TF
Group=-1

[01000003]
Name=E1T2
Script=01000001
TaskForce=01000002
VeteranLevel=1
MindControlDecision=0
Loadable=no
Full=no
Annoyance=yes
GuardSlower=no
House=<none>
Recruiter=no
Autocreate=yes
Prebuild=no
Reinforce=yes
Droppod=no
UseTransportOrigin=no
Whiner=yes
LooseRecruit=yes
Aggressive=no
Suicide=no
Priority=5
Max=10
TechLevel=0
Group=-1
OnTransOnly=no
AvoidThreats=no
IonImmune=no
TransportsReturnOnUnload=no
AreTeamMembersRecruitable=yes
IsBaseDefense=yes
OnlyTargetHouseEnemy=no

[AITriggerTypes]
01000000=E1,01000003,<all>,1,-1,<none>,0000000000000000000000000000000000000000000000000000000000000000,5000.000000,5000.000000,5000.000000,1,0,1,0,<none>,1,1,1

[AITriggerTypesEnable]
01000000=yes

[Basic]
IgnoreGlobalAITriggers=yes
```

### Steps to reproduce

1. put the map I have attached below in game folder
2. two human players set in 1 and 5, other positions are any allied AIs
3. player 1-4 as a team, and 5-8 another team
4. fire up the game and wait

### Expected behaviour

everything goes well

### Actual behaviour

RE occurs usually before 10k frames

### Additional context

test map and debug.log
https://drive.google.com/drive/folders/1imXbtZOAaz9dQGL6ij6L_VHy7YJUSbqP?usp=sharing

**Comment by handama** [comment]
I copied Mission_Move function of b27 to b28, and fixed the problem.
https://drive.google.com/drive/folders/1imXbtZOAaz9dQGL6ij6L_VHy7YJUSbqP?usp=sharing

**Comment by FS-21** [comment]
I think that I can reproduce the error but after your comment I want to compare changes of that function in b27 & b28.
I thought nobody touched that function in months 🤔
When I arrive home I'll compare the code.

Can you do more playtests alternating b27 &b28 in meanwhile?

**Comment by Metadorius** [comment]
@FS-21 did you succeed at fixing the issue?
