### ISSUE TITLE
Custom AISafeDistance for each TeamTypes

### ISSUE THREAD

**Issue by deathreaperz** [Phobos-developers/Phobos#664]
### First check

- [X] The suggestion is **NOT** related to functionality of Ares, HAres, Kratos or any other YR engine extension.
- [X] The suggested feature / enhancement is **NOT** implemented in Ares/Phobos yet and the existing possibilites are not viable or good enough to achieve the wanted result.
- [X] I agree to elaborate the details if requested and provide thorough testing if the feature is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I thought out how the feature / enhancement should work and described it in the most detailed and clear way.

### Description

I wonder if it's possible to customize AISafeDistance for each TeamTypes, so that we have variant "Gather at Enemy Base" locations.

### INI code

```ini
[A TeamType]
AISafeDistance=(integer, default to [General]>AISafeDistance)
```

**Comment by FS-21** [comment]
Ares have that, right?

https://ares-developers.github.io/Ares-docs/new/scripts.html#gather-at-enemy-53

**Comment by secsome** [comment]
> Ares have that, right?
> 
> https://ares-developers.github.io/Ares-docs/new/scripts.html#gather-at-enemy-53

Using script is enough then

**Comment by deathreaperz** [comment]
Right, seems there is a misunderstanding here. Gather at Enemy Base and AISafeDistance is RA2's. What I mean is to allow TeamTypes to have variant AISafeDistance, rather just one AISafeDistance from [Generals].
