### ISSUE TITLE
Customize Behind Animation

### ISSUE THREAD

**Issue by Daiki9527** [Phobos-developers/Phobos#666]
### First check

- [X] The suggestion is **NOT** related to functionality of Ares, HAres, Kratos or any other YR engine extension.
- [X] The suggested feature / enhancement is **NOT** implemented in Ares/Phobos yet and the existing possibilites are not viable or good enough to achieve the wanted result.
- [X] I agree to elaborate the details if requested and provide thorough testing if the feature is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I thought out how the feature / enhancement should work and described it in the most detailed and clear way.

### Description

For some reason, some dummy unit should not be seen, however the BEHIND Anim could be an issuse.

### INI code

```ini
[TechnoTypes]
Behind=XX.shp                             ;Default to [General]=>Behind=
ShowBehindAnim=yes/no
```

**Comment by Starkku** [comment]
Setting `CanBeHidden=true` on the TechnoType's image (`artmd.ini` entry) will prevent display of the animation already.
