### ISSUE TITLE
 MinimapColor= doesn't work with XNA CnCNet Client Spawner INI file

### ISSUE THREAD

**Issue by FS-21** [Phobos-developers/Phobos#673]
### First check

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

### Description

MinimapColor= tag is readed only in rulesmd.ini So any Game Option from the XNA CnCNet launcher that changes the radar colours are ignored by Phobos.

The thing is that you can change graphics and other variables from the INI files through the XNA client but this radar tag isn't re-readed.

### Phobos Version

https://github.com/Phobos-developers/Phobos/actions/runs/2446749334

### Steps to reproduce

1.
Use any Phobos Develop build.

2.
In these rulesmd.ini sections:
[Riparius]
[Cruentus]
[Vinifera]
[Aboreus]

Add:
MinimapColor=0,255,0

That draws resources in GREEN colour in the radar.

3.
Now create a Game Option in the XNA CnCNet Client with these lines
[Riparius]
MinimapColor=255,0,0

[Cruentus]
MinimapColor=255,0,0

[Vinifera]
MinimapColor=255,0,0

[Aboreus]
MinimapColor=255,0,0

4.
Play with the new Game Option enabled and the resources should be drawed in RED colour in the radar instead of green.

### Expected behaviour

Resources should be drawed in Red in the minimap instead of the original value in rulesmd.ini

### Actual behaviour

The new radar color values are ignored if written outside the rulesmd.ini

**Comment by FS-21** [comment]
Yes, the original rulesmd.ini tags used by those 4 resources (image, value, spread, growth,  etc).
Maybe another hook is needed or place the current one in another address.

**Comment by Starkku** [comment]
I will take a look at this later.

**Comment by FS-21** [comment]
Yes, declaring [Tiberiums] solves the bug.
