### ISSUE TITLE
Unit killed by radiation with a tag of event 48 (Destroyed by anything) can‘t take effect

### ISSUE THREAD

**Issue by prry123** [Phobos-developers/Phobos#676]
### First check

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [x] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

### Description

First, make a unit attaches a tag with event 48 (Destroyed by anything)  in map editor. Then train a desolater deployed to kill this unit in the game. Unit killed by radiation, but nothing happens. It should output “6” as the trigger action. The radiation of terrorist in FV or demolitions truck is the same. I tried it in YR1001. it won't happen.

### Phobos Version

build28

### Steps to reproduce

1.make a unit attaches a tag with event 48 (Destroyed by anything)  in map editor. 
2.train a desolater deployed to kill this unit in the game.
3.
...

### Expected behaviour

It should output “6” as the trigger action

### Actual behaviour

Nothing happens.

### Additional context

![image](https://user-images.githubusercontent.com/81023827/174846982-ce0b5ebe-5fd8-463a-923a-bcd997a51762.png)

![image](https://user-images.githubusercontent.com/81023827/174848159-db948565-8804-4bf6-80ba-08831cbdeee8.png)

**Comment by Metadorius** [comment]
@Otamaa can you look into this one?

**Comment by chaserli** [comment]
This should happen only for Units. Infantries would not be affected
