### ISSUE TITLE
Global variable cannot be saved & Unable to load game save

### ISSUE THREAD

**Issue by kyonkonyan** [Phobos-developers/Phobos#681]
### First check

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

### Description

1.only on [Build 28]
  game save cannot be load

2.on [Build 28] and earlier versions
  the current level global variable is saved successfully, but the second level cannot read this global variable

### Phobos Version

Build 28

### Steps to reproduce

A.game save cannot be load
1.save game
2.load game

B.global variable
1.mission map level 1 set global variable and win this level
2.mission map level 2 read global variable
3.show global variable 

### Expected behaviour

A.game save cannot be load
1.save game
2.load game
3.success

B.global variable
1.mission map level 1 set global variable and win this level
2.mission map level 2 read global variable
3.show global variable 
4.it‘s 1

### Actual behaviour

A.game save cannot be load
1.save game
2.load game
3.FE

B.global variable
1.mission map level 1 set global variable and win this level
2.mission map level 2 read global variable
3.show global variable 
4.it‘s 0

**Comment by kyonkonyan** [comment]
经过测试发现不能读取存档是由trajectory导致的，已经被Starkku在2022 年 7 月 21 日修复

**Comment by Metadorius** [comment]
All good then, thanks for reporting 👍
