### ISSUE TITLE
Please release more often!

### ISSUE THREAD

**Issue by Zorbung** [Phobos-developers/Phobos#682]
### First check

- [X] The suggestion is **NOT** related to functionality of Ares, HAres, Kratos or any other YR engine extension.
- [X] The suggested feature / enhancement is **NOT** implemented in Ares/Phobos yet and the existing possibilites are not viable or good enough to achieve the wanted result.
- [X] I agree to elaborate the details if requested and provide thorough testing if the feature is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I thought out how the feature / enhancement should work and described it in the most detailed and clear way.

### Description

Please release more often so we can include new features in our mods. Last release was 10 months ago! You know you can't fix everything in one go, no one can, so what's the point? There will always be issues. Mod users can find more bugs than mod developers ever can, which will also naturally help you with testing. Having a release per year doesn't help anyone really...

### INI code

```ini
[SomeSection]
SomeKey=SomeValue
```

**Comment by SMxReaver** [comment]
Build 28 came out May 15th, use the "Release" section of GitHub to find the most up to date release; do not rely on the main GitHub page to show you all of the available releases.

https://github.com/Phobos-developers/Phobos/releases

This can probably be closed lol

**Comment by Zorbung** [comment]
@SMxReaver I'm always using that link. Build 28 is still debug. Even from the file size you can tell that. Pre-release is not release. It also has debug text on-screen and it's not usable in mods! Have you even tried it at least once?

**Comment by Metadorius** [comment]
> It also has debug text on-screen and it's not usable in mods!

Careful reading of documentation is certainly not your virtue. 😄

**Comment by Zorbung** [comment]
@Metadorius 
_"You can hide the warning by specifying the build number after -b= as a command line argument (for example, -b=1 would hide the warning for development build #1 of Phobos)."_
This doesn't make it a release. Edited main post for clarification.

**Comment by SMxReaver** [comment]
> 

Yes, in fact before I quit work on Final War altogether I was actively testing Build 28 and testing PRs for features to make it into the next Build (29) or 0.3. It works just fine in my own version of FW containing a much better solution to 0x0 building hacks, have you tried it before? Is one line of text that you can disable an issue if you are in dire need to release a mod update? ROTE has been testing builds via their updater and have an active playerbase that helps out with online stability testing. 

You appear to be only interested in reaping the rewards of Phobos development by waiting for an official release, help test Build 28/PRs like everyone else who wants another "official" release.

**Comment by Zorbung** [comment]
@SMxReaver 
I'm simply making a reasonable request. Release is for public use, debug is for devs and testers only. It's users' choice if they test or not. Forcing them to use debug and become testers for you is **not** okay.

Breaking development into logical stages is useful for everyone. Modders can update their mods and Phobos devs can have a break and a feeling of completion.

Postponing the release version for so long can burnout devs and decrease public interest, no one wins. Lots of project died out this way.

Anyway, calling me a leech just because I'm interested in Phobos is a bit out of line. This was just a suggestion out of respect for your own work. Who lols at me for that is just loling at their own team.

**Comment by Metadorius** [comment]
We know pretty well that we should've released the next version lots of time ago. But it didn't happen, because, you know, this is not a paid project and people work on it (or not) out of their own interest. And this is also a community project, if you want something to happen - then participate in making that happening instead of arguing on how your criticism is appropriate or not.

Locking to stop the drama.

**Comment by Metadorius** [comment]
P.S. There isn't much difference between devbuild (it's not debug, mind you) and release versions, but if you absolutely feel a need to ship release builds only - you are free to clone the repository, install the build tools and run a script to do a release build for yourself.
