### ISSUE TITLE
Vehicles cannot force fire friendly infantry-only grinder

### ISSUE THREAD

**Issue by chaserli** [Phobos-developers/Phobos#685]
### First check

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

### Description

When selecting vehicles to force target an infantryabsorb-only grinder, the force fire cannot happen.

### Phobos Version

b28+

### Conditions to reproduce

see INI code below

### INI code

```ini
[GrinderType]
Grinding=yes
InfantryAbsorb=yes
UnitAbsorb=no
```

### Steps to reproduce

use vehicles to force fire your own infantry absorb-only grinder

...

### Expected behaviour

![5~A @FA$SCN PW(OWV0$@AO](https://user-images.githubusercontent.com/9932846/176866518-7d4cc471-04ee-4f71-bdab-da2f942ba5e7.png)

### Actual behaviour

![ARCFYSVN( (`Z9T}OPQFHA](https://user-images.githubusercontent.com/9932846/176866492-6590bc4b-1660-4f2e-bda0-4ccaf7d0c5c3.png)

**Comment by Starkku** [comment]
The wrong cursor is a non-issue (it is supposed to display cursor for NoEnter action instead of the select cursor from vanilla but MO has this improperly configured for Field Bureau), but the lack of ability to force-fire is a real bug.

**Comment by chaserli** [comment]
Confirmed fix
