### ISSUE TITLE
A random jumpjet crush on phobos

### ISSUE THREAD

**Issue by ststl-s** [Phobos-developers/Phobos#690]
### First check

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

### Description

At the beginning of this mission, there is a kirov airship that would be crush onto the golden gate bridge, unfortunately, there is a player who used a modified rules found out the kirov would always crush——the mission itself——rather than onto the bridge. Yes, he set the kirov to explode on the air (Crushable=no), the game would not be into fatal error at that stage, so it is for sure a jumpjet crush.
So we made some measures to find out the problem, the original rules is ok, so the problem is related to his modify (that would be listed below), and the original ares is ok, so the problem is taken by phobos. Then we found the problem is between b23 to b24, there is something changed here and around the "image altswap" and "anim layer", however, the problem is still unknown. The fatal error can only be repeated on his computer, but there was nothing happened on the others. From the dmp, we found the problem is about shadow drawing.
The player who found the problem changed his rules and found out the problem is from the Hunter-Seeker which he changed its three explosion anim into one who has a customed palette, without this there would not be the problem. So in general, Hunter-Seeker's explosion anim changing would be related with jumpjet crush, maybe there would be something unknown between them, perhaps, anim layer problem?

### Phobos Version

b24, b25, b26, b27, b28

### Conditions to reproduce

Win10
Mental Omega 3.3.6 Soviet 02
Ares
Phobos-b24/25/26/27/28
cncddraw

### INI code

```ini
[SUNB]
Explosion=SUNBURN2

2443=SUNBURN2

[SunburstBombWH]
AnimList=SUNBURN2

In art:
[SUNBURN2]
Translucent=no
UseNormalLight=yes
Report=Explosion15
Crater=yes
Scorch=yes
CustomPalette=tianim.pal
```

### Steps to reproduce

1. Add a explosion anim to `[SUNB]`
2. Fatal error

### Expected behaviour

When kirov dead (Projectile explode moment) cause Fatal Error EIP 0x7BAEA1 (XSurface::GetPixel)
![QQ图片20220704183947](https://user-images.githubusercontent.com/103478314/177138540-dcb81a23-88a2-4c5f-8054-a1868e51cc74.jpg)

### Actual behaviour

Mental Omega Soviet 02

### Additional context

[snapshot-20220703-231333.zip](https://github.com/Phobos-developers/Phobos/files/9038761/snapshot-20220703-231333.zip)
extcrashdump.dmp exceed upload file size limit.

**Comment by ststl-s** [comment]
![image](https://user-images.githubusercontent.com/103478314/177140315-d89954ee-fed7-4b9f-a407-d151e5128e6d.png)
Appear Appear from these commit（Not sure, but b23 is no such problem）

**Comment by ststl-s** [comment]
I can't reproduce this fatal error too. It may be caused by illegal memory access in other functions, such as array out of bounds. And he said that the problem was no longer cause by hunterseeker's anim now but still appear.

**Comment by mevitar** [comment]
Did he modify the Kirov art entries too? To be more specific, what are the values of UseBuffer= and DisableShadowCache=?

**Comment by ststl-s** [comment]
> Did he modify the Kirov art entries too? To be more specific, what are the values of UseBuffer= and DisableShadowCache=?


Nope. 
![tmp](https://user-images.githubusercontent.com/103478314/180597785-d239b6c0-d992-43b5-884c-46f9d94524ec.png)

**Comment by Metadorius** [comment]
So is the problem reproducible? If it's not we should close it until we find a way to reproduce it consistently.

**Comment by Metadorius** [comment]
Also isn't #655 the same issue?

**Comment by Starkku** [comment]
> Also isn't #655 the same issue?

I believe they are the same issue yes.

**Comment by ststl-s** [comment]
This problem occurs randomly and occurs when the projectile that can kill ZEP is about to hit.

At present, he can only confirm that it will not happen if he does not use Phobos.

Close this issue first. If anyone else has the same problem, check this issue again.
