### ISSUE TITLE
RadHasInvoker Error

### ISSUE THREAD

**Issue by kyonkonyan** [Phobos-developers/Phobos#700]
### First check

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

### Description

if RadHasInvoker = yes，radiation damage after the attacker dies will lead to FE

### Phobos Version

Build 29

### INI code

```ini
[Radiation]
……
……
RadHasInvoker=yes
```

### Steps to reproduce

1.Let RadHasInvoker=yes
2.Let the attacker cause a lot of radiation
3.Kill the attacker
4.Let the unit enter the radiation
![1](https://user-images.githubusercontent.com/28522954/178302992-8a03d8ce-63de-4987-9d61-302f5a31bb68.gif)

### Expected behaviour

It will cause damage normally

### Actual behaviour

FE

**Comment by Starkku** [comment]
Has already been fixed, can test latest development nightly build to confirm

**Comment by kyonkonyan** [comment]
> Has already been fixed, can test latest development nightly build to confirm
nope
i used this version : github.com/Phobos-developers/Phobos/releases/download/build-29/Phobos.dll

**Comment by chaserli** [comment]
> > Has already been fixed, can test latest development nightly build to confirm
> > nope
> > i used this version : github.com/Phobos-developers/Phobos/releases/download/build-29/Phobos.dll

It's nighly builds we were talking about, not devbuilds, go to https://github.com/Phobos-developers/Phobos/actions and fetch the first successful build

**Comment by kyonkonyan** [comment]
> > > 已经修复，可以测试最新的开发夜间版本以确认没有
> > > 我使用这个版本：
> > > github.com/Phobos-developers/Phobos/releases/download/build-29/Phobos.dll
> 
> 这是我们谈论的几乎构建，而不是 devbuild，请转到https://github.com/Phobos-developers/Phobos/actions`develop`并获取分支的第一个成功构建

okay,thanks
