### ISSUE TITLE
Seems AE animation's owner is always set to attached unit's owner, not set to unit launched this AE. Even if animation is set Damage.DealtByInvoker=true

### ISSUE THREAD

**Issue by NoobLCH** [Phobos-developers/Phobos#715]
### First check

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

### Description

Seems that AE animation's owner is always set to attached unit's owner, not consider who is launched this AE.
Like title says:
Unit A fire warhead set AE to Unit B, the AE owner is the B's  owner, not A that fire the warhead instead. The expect behaviour is that the AE is owned by A.
Even if set that AE animation with Damage.DealtByInvoker=true, it's still nothing work.

For example:
In Mental Omega, the Shadray Tank's AA weapon's warhead will attch the enemy an AE named "FAKESHAD", the FAKESHAD is set damage to the attached enemy unit, but not damage friendly unit beacuse FAKESHAD's warhead have AffectAllies=no ( Exactly, is AffetsOwner=no)
After phobos build29, the FAKESHAD animation cannot damage enemy anymore, because FAKESHAD's owner is the attached enemy unit (FAKESHAD's owner expect is shadary tank). Set FAKESHAD with Damage.DealtByInvoker=true is not work.
But if you set FAKESHAD's warhead with AffectsOwner=yes, it will damage the attched enemy unit again.

Another example is krukolv's Radbeams, it's warhead AE ERAD can not harm enemy anymore, even enemy attached ERAD can harm krukolv's owner units.

### Phobos Version

Build29 Pre-release

### Conditions to reproduce

Win10
Mental Omega 3.3.6
Ares3.0p1 + phobos build29 (not daily build)
cnc-ddraw

### INI code

```ini
;In rules
[ShadrayWaveAAWH]
....
AttachEffect.Animation=FAKESHAD
AffectsAllies=no
.....

;In art
[FAKESHAD]
Normalized=no
Damage=3
DamageRadius=10000
Warhead=FakeShadWH
Rate=200
;It's no work about add this:
Damage.DealtByInvoker=true

;In rules:
[FakeShadWH]
...
AffectsAllies=no
AffectsEnemies=yes
...
```

### Steps to reproduce

(Using Shadray as examle)
1. Use phobos b29+ares3.0p1 with Mental Omega. Set shadray's AA weapon damage to 1( cut weapon damage, just use animation damage)
2. Using shadray attack enemy air unit. Will see shadray can not damage it.
3. [FAKSHAD] add Damage.DealtByInvoker=true, it still not damage enemy air unit.
4. [FakeShadWH] set AffectsOwner=yes, it can damage enemy air unit again.

### Expected behaviour

After the animation set Damage.DealtByInvoker=true, the AE should consider the unit who launched this AE as it's owner.

### Actual behaviour

The AE always set the unit which attached this AE as owner.

**Comment by chaserli** [comment]
On the contrary, you may need to detach the ownership of the anim as well as the warhead

**Comment by Starkku** [comment]
Not a bug, this is intended behaviour and is in fact mentioned in documentation. Presently it is also technically impossible for the AE animation to know what unit fired the weapon it was created by.
