### ISSUE TITLE
Chinese error code problem when saving games with Phobos

### ISSUE THREAD

**Issue by AngelaSure** [Phobos-developers/Phobos#716]
### First check

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

### Description

Chinese error code problem when saving games with Phobos Build 29. When the Chinese name of the saving game is used, error code will occur. The input method used is Microsoft input method.

### Phobos Version

Build 29

### Steps to reproduce

1.Saving game using Chinese input method.
2.
3.
...

### Expected behaviour

Chinese input is normal.

### Actual behaviour

Error code occur.

**Comment by Belonit** [comment]
Have you tried older Phobos builds ? For example [0.2.2](https://github.com/Phobos-developers/Phobos/releases/tag/v0.2.2.2) and [0.2](https://github.com/Phobos-developers/Phobos/releases/tag/v0.2) ?

**Comment by Metadorius** [comment]
Fixed in #717.

**Comment by AngelaSure** [comment]
Thanks for fixing! By the way, when will the official version of 3.0 be released?




---Original---
From: ***@***.***&gt;
Date: Thu, Aug 4, 2022 19:03 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Phobos-developers/Phobos] Chinese error code problem when saving games with Phobos (Issue #716)




 
Fixed in #717.

**Comment by Metadorius** [comment]
Ideally I would want 0.3 to be released before this summer, the biggest remaining change that is left is refactoring of script actions numbering.

**Comment by Metadorius** [comment]
I mean before this summer ends, sorry.
