### ISSUE TITLE
Spawned voxel using Anim2Unit do not respect terrain position

### ISSUE THREAD

**Issue by Danielovich7** [Phobos-developers/Phobos#719]
### First check

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

### Description

Usng Anim2Unit logic to create husks of destroyed vehicles, I noticed husks will always be perfectly horizontal on any terrain tile, as if they were on flat terrain. So, it looks a bit odd on slopes, as the husk will appear as if it was on a flat tile.

Rise of the East does not have this issue, and I tried to copy its code as much as possible but it doesn't change a thing. Idk if the problem is my code or if Phobos sometimes fail to consider terrain when creating a unit with Anim2Unit on some specific conditions.

### Phobos Version

Build 29

### Conditions to reproduce

Give a vehicle a DestroyAnim= that spawns another vehicle that acts as a husks. Destroy that vehicle on a slope and see if the husk obeys the terrain's rules.

### INI code

```ini
Add the corresponding vehicle and animation under [VehicleTypes] and [Animations]

;In Rulesmd.ini
[HTNK]
...
DestroyAnim=HTNKHUSKANIM

[HTNKHUSK]
Prerequisite=GAWEAP
TechLevel=-1
Strength=125
Armor=huskarmor ;0% armor
Death.Countdown=120
DontScore=yes
CrateGoodie=no
Insignificant=yes
IsSelectableCombatant=no
Trainable=no
AttachEffect.Animation=HUSKFIRE ;simple fire animation
AttachEffect.Duration=-1
ImmuneToAbduction=yes
HealthBar.Hide=yes
DeathWeapon=MedVehDeathWeapon ;normal death weapon
Explodes=yes
Turret=yes
IronCurtain.Modifier=0
IronCurtain.Modifier=0

;In artmd.ini
[HTNKHUSKANIM]
Image=INVISO
Start=0
End=0
CreateUnit=HTNKHUSK
CreateUnit.Facing=-1
CreateUnit.RandomFacing=no
CreateUnit.InheritFacings=yes
CreateUnit.InheritTurretFacings=yes 
CreateUnit.RemapAnim=yes
CreateUnit.Mission=Sleep
CreateUnit.Owner=Victim
CreateUnit.ConsiderPathfinding=no
```

### Steps to reproduce

1. Give a unit a husk using Anim2Unit logic
2. Bring it on a slope and destroy it
3. Observe

### Expected behaviour

The husk should be inclined according to the terrain tile which it was spawned on

### Actual behaviour

The husk stays flat, as if it was on a flat tile.

### Additional context

![image](https://user-images.githubusercontent.com/79372870/182412474-b1d1f860-d31b-4de0-ba66-0dbcc1a96966.png)

**Comment by Starkku** [comment]
Not a Phobos bug, in fact it is not a bug at all. This happens because Teleport Locomotor (which is the default, your husk vehicle has no locomotor specified) does not implement slope tilting behaviour. Change the Locomotor to Drive one for an example and it should work like expected in that regard.

**Comment by Danielovich7** [comment]
You are indeed right, the problem resolved itself using a correct locomotor. Thank you and sorry for the useless bug report.
