### ISSUE TITLE
Defensive buildings controlled by Yuri Prime are unable to fire

### ISSUE THREAD

**Issue by Ampere1990** [Phobos-developers/Phobos#731]
### First check

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

### Description

[https://www.bilibili.com/video/BV1Ea411R7Rp/](url)
As the title said, is that true of everyone? Or is it just me?

### Phobos Version

Phobos 29

### Conditions to reproduce

YR1.001+Ares3.0

### Steps to reproduce

1. Yuri's Revenge 1.001
2. Ares 3.0
3. Phobos 29

### Expected behaviour

Buildings controlled by Yuri Prime should be able to fire

### Actual behaviour

Buildings controlled by Yuri Prime are unable to fire

### Additional context

[https://www.bilibili.com/video/BV1Ea411R7Rp/](url)

**Comment by chaserli** [comment]
Can you test if #739 solves your problem?
这个情况应该是b28后才有的，你看一下链接的PR是否能够解决问题，记得在对应链接里面反馈
