### ISSUE TITLE
Add Chinese(Simplified) input method and characters supporting.

### ISSUE THREAD

**Issue by Universal-UNION** [Phobos-developers/Phobos#753]
### First check

- [X] The suggestion is **NOT** related to functionality of Ares, HAres, Kratos or any other YR engine extension.
- [X] The suggested feature / enhancement is **NOT** implemented in Ares/Phobos yet and the existing possibilites are not viable or good enough to achieve the wanted result.
- [X] I agree to elaborate the details if requested and provide thorough testing if the feature is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I thought out how the feature / enhancement should work and described it in the most detailed and clear way.

### Description

Add Chinese(Simplified) input method and characters supporting.
Currently when trying to input Chinese(Simplified) will cause some random characters to appear.

### INI code

```ini
[SomeSection]
SomeKey=SomeValue
```

**Comment by Belonit** [comment]
@Universal-UNION Is it possible to solve this problem only by editing the font?

**Comment by MapleEve** [comment]
> @Universal-UNION Is it possible to solve this problem only by editing the font?

It's actually a cnc spawner issue. ZZeus has fixed this.
