### ISSUE TITLE
Ares GBK code support issue.

### ISSUE THREAD

**Issue by MapleEve** [Phobos-developers/Phobos#789]
### First check

- [X] The issue is not introduced by Phobos or any other engine extension, such as Ares, Kratos etc.
- [X] The issue wasn't fixed in the most recent version of Ares/Phobos yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

### Description

Recently, we are working on support Ares + Phobos env and the in-room players can use GBK or Arabic names etc.

But when we patch the specfic mem address that Ares use, it will destroy the PCX loading.

The spawn.ini username is ASCII only and it bypassed GBK or other codec. 

### Conditions to reproduce

latest Ares + Phobos

### INI code

we don't need that. Just use vanllia game.

### Steps to reproduce

1. Change a username into GBK code like 你好123
2. Load the game
3. In the game loading screen, it only shows 123 instead of 你好123
...

### Expected behaviour

username supports GBK or other wide codec.

### Actual behaviour

username only supports ASCII

**Comment by MapleEve** [comment]
We've rewire the RbpAres function since the C make is ASCII only.
https://github.com/RamboPlayCom/ZZeus
Release is here.

**Comment by Belonit** [comment]
> We've rewire the RbpAres function since the C make is ASCII only. https://github.com/RamboPlayCom/ZZeus Release is here.
It seems that this is not a Phobos problem. I think it's an Ares or cncnet bug. Since there is no hope of updating Ares, check out this repository - https://github.com/CnCNet/yrpp-spawner

**Comment by Metadorius** [comment]
I don't think RamboPlay cares about contributing to the community, so don't bother. If they did - they would open a PR already.
