### ISSUE TITLE
Customize storage logic

### ISSUE THREAD

**Issue by KuroNoSeiHai** [Phobos-developers/Phobos#798]
### First check

- [X] The suggestion is **NOT** related to functionality of Ares, HAres, Kratos or any other YR engine extension.
- [X] The suggested feature / enhancement is **NOT** implemented in Ares/Phobos yet and the existing possibilites are not viable or good enough to achieve the wanted result.
- [X] I agree to elaborate the details if requested and provide thorough testing if the feature is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I thought out how the feature / enhancement should work and described it in the most detailed and clear way.

### Description

Make can which specific types of tiberiums use storage logic.  Other types of tiberiums will convert to money directly. 

### INI code

```ini
[Tiberium]
UseStorage=yes/no
```

**Comment by FS-21** [comment]
Already implemented by me :-/

**Comment by KuroNoSeiHai** [comment]
> 

I mean other types of tiberiums will convert to money directly, only specific types of tiberium use storage logic.
The "Custom Resource Storage" just transform all types of tiberium to defined and store it.

**Comment by KuroNoSeiHai** [comment]
> Already implemented by me :-/

I open an issue, now the "Custom Resource Storage" still store all types of tiberium, just transform them to one type.
