### ISSUE TITLE
Custom Iconography does not work with CnC-DDraw

### ISSUE THREAD

**Issue by Musketmarine** [Phobos-developers/Phobos#8]
The custom icon works on other renderers, but not CnC-DDraw. I remember talking with Kerbiter about this, and i've heard no confirmation or anything that it has been patched in Phobos yet. So i'm reposting it here to keep it fresh on everybody's minds.

**Comment by Metadorius** [comment]
It's possible to fix that in Phobos but it's better to make CnC-DDraw's override of icon optional based on some config key.

**Comment by FS-21** [comment]
If this issue is the one that CNCDDraw couldn't replace the YR game icon with a custom one this can be closed because CNCDDraw already supports it.
