### ISSUE TITLE
Grinding units with passengers or infected by terror drones gives incorrect refund display number

### ISSUE THREAD

**Issue by chaserli** [Phobos-developers/Phobos#800]
### First check

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

### Description

Grinding units with passengers or infected by terror drones gives incorrect refund display number

### Phobos Version

b28-current develop

### Conditions to reproduce

enable Grinding.DisplayRefund

### Steps to reproduce

Grind a transport with passengers or infected by terror drone

### Expected behaviour

shows the correct refund number

### Actual behaviour

the number takes only the vehicle into account

### Additional context

Refactor `BuildingExt::DoGrindingExtras`, check the house balance before the `UnitClass_PerCellProcess_Grinding` hook and do like #775

**Comment by Starkku** [comment]
Should be fixed in 97c0a350bf7c6f52450a3fb762df931af876fc31.
