### ISSUE TITLE
"CreateUnit.Owner" Doesnt Work

### ISSUE THREAD

**Issue by Daiki9527** [Phobos-developers/Phobos#859]
### First check

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

### Description

i used CreateUnit.Owner=Civilian
The new created unit is not Civilian
And other options all resulted in the behavior of the option :invoker

### Phobos Version

build 33

### INI code

```ini
[anim01]
Layer=ground
Report=ExplosionBarrel
Start=0
End=39
CustomPalette=animx.pal
CreateUnit=tank01
CreateUnit.Owner=Civilian
CreateUnit.RemapAnim=false
CreateUnit.Mission=Sleep
CreateUnit.Facing=0
CreateUnit.RandomFacing=true
CreateUnit.InheritFacings=false
CreateUnit.InheritTurretFacings=false
CreateUnit.AlwaysSpawnOnGround=true
CreateUnit.ConsiderPathfinding=true
CreateUnit.SpawnAnim=anim02

[anim02]
Image=anim01
Layer=ground
Start=40
End=49
CustomPalette=animx.pal
```

### Steps to reproduce

.

### Expected behaviour

created unit should be civilian, but it belongs to my house.

### Actual behaviour

all other options resulted in the behavior of the option :invoker

**Comment by Rhosalth7** [comment]
This is a known issue and is stated in the phobos docs: *Due to technical constraints, infantry death animations including Ares’ InfDeathAnim cannot have CreateUnit.Owner correctly applied to them. You can use Ares’ MakeInfantryOwner as a workaround instead, which should function for this use-case even without MakeInfantry set.*

**Comment by Daiki9527** [comment]
> This is a known issue and is stated in the phobos docs: _Due to technical constraints, infantry death animations including Ares’ InfDeathAnim cannot have CreateUnit.Owner correctly applied to them. You can use Ares’ MakeInfantryOwner as a workaround instead, which should function for this use-case even without MakeInfantry set._

I didn't use InfDeathAnim in the warhead

**Comment by Daiki9527** [comment]
Ran a few test, It was kratos causes this,  sorry for the inconvenience
