### ISSUE TITLE
Loading into skirmish, Exception code: C0000005 at 0047C2E7 

### ISSUE THREAD

**Issue by ZachPLin** [Phobos-developers/Phobos#860]
### First check

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

### Description

Crash happens when the loading bar reaches about 60%. 0.33 has not issue loading into the game. This is a new problem for 0.34.

### Phobos Version

0.34

### Steps to reproduce

1. Select any map
2. Start game
3. Crash

### Expected behaviour

Load into skirmish. 

### Actual behaviour

Internal error. Exception code: C0000005 at 0047C2E7

0047C2E7 can be found in a known list of IE.
Crash was when a cell's radar color was being retrieved from an Isometric Tile, which might be corrupt.
Can happen when loading a map that uses tiles that are not present; like when FA2 asks "map is corrupt, do you want to attempt fix?".

**Comment by chaserli** [comment]
Should have been fixed in 6e3a66d
