### ISSUE TITLE
The task force with map editor has built-in passengers, so it can't attack automatically.

### ISSUE THREAD

**Issue by Jia1322558777** [Phobos-developers/Phobos#867]
### First check

- [x] The issue is not introduced by Phobos or any other engine extension, such as Ares, Kratos etc.
- [X] The issue wasn't fixed in the most recent version of Ares/Phobos yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

### Description

The task force with map editor has built-in passengers, so it can't attack automatically.

### Steps to reproduce

1The unit is allowed to carry passengers and attack outside.
.Figure editor to create a task force
2.Trigger built-in passenger

...

### Expected behaviour

Passengers can't attack automatically!

### Actual behaviour

Passengers can't attack automatically!

**Comment by chaserli** [comment]
Same issue as #778? if yes, already fixed in #779

**Comment by Jia1322558777** [comment]
It shouldn't be the same type.

**Comment by Jia1322558777** [comment]
> 与相同的问题#778？如果是，已经固定在#779
I don't think it's the same one. It was triggered by the forces of the map editor.

**Comment by chaserli** [comment]
> > I don't think it's the same one. It was triggered by the forces of the map editor.
I can't understand what you were saying.
Try with the latest build first, if it doesn't solve your issue then rephrase in a comprehensible way
